### ISSUE TITLE
Quiz Question Inconsistency

### ISSUE THREAD

**Issue by Piptendo** [ObliqueNET/Terra#100]
https://puu.sh/AtbkJ/951bff3779.png
Screenshot says it all.

I imagine the fix is changing the name in the dex entry from "Farfetch'd" to "[Pokemon]". 👍 
Thanks for kicking ass at what you guys do!

**Comment by Kitsune30** [comment]
Yep, it's a known issue, there are a few others. It's because the plugin
doesn't understand fancy symbols such as apostrophes and accents. It's
planned to be fixed eventually

**Comment by Vohras2** [comment]
Closing this since it's over a year old.
