### ISSUE TITLE
Lost Pokeballs

### ISSUE THREAD

**Issue by Mondrox133** [ObliqueNET/Terra#102]
My inventory was completely cleared,  and i lost all my pokeballs. i had like 20 regular 10 great and 20 timer balls from voting. i teleported home and then bam nothing

**Comment by Kayouri** [comment]
Were you ever helped with this issue?
For future reference; if something like this happens, it is a lot easier to get a hold of Staff for them to fix the issue on our discord, in the support channel. You will get helped a lot quicker.

**Comment by Rasgnarok** [comment]
I am closing this because it is outdated, please open a new one if it hasn't yet been addressed!
