### ISSUE TITLE
Movement plates disappearing glitch

### ISSUE THREAD

**Issue by BaconKing05** [ObliqueNET/Terra#103]
i was trying to make an infinite loop of movement plates then the last movement plate i was going to put down disappeared and then i tried it again and it disappeared so i tried moving it to another location but it dissapeared there aswell.

**Comment by Vohras2** [comment]
You can't make a perfect infinite loop. Need to fill a space with a block to slide over. If you relog, you'll have the movement plate. Anyways, closing this since it's from forever ago, and not really a bug.
