### ISSUE TITLE
Wiki Biome Bug

### ISSUE THREAD

**Issue by StabWaifu** [ObliqueNET/Terra#107]
![image](https://user-images.githubusercontent.com/7892190/43173891-0e856d5a-8f6c-11e8-8f09-6323467b589f.png)

If you add the apostrophe it does this. Shika also said that it does it with pokemon like Aegislash that just don't spawn, instead of just saying "this pokemon doesn't spawn".

**Comment by Rasgnarok** [comment]
Please re-open if this is still an issue.
