### ISSUE TITLE
I lost of all of my skills

### ISSUE THREAD

**Issue by cjn213** [ObliqueNET/Terra#108]
I had about 40 in all of my skills and after the 6.3.3  update was put into effect and the server restarted I had lost them all when I entered if I could get them back that would be fantastic. My in game name is oasis_wolf

**Comment by Rasgnarok** [comment]
Can you list what levels they were?

**Comment by cjn213** [comment]
all of these are from my memory so they may not be exactly right
mining:43
woodcutting:36
martial arts: 1 (currently bugged so I cant gain any and I need 40 for a quest)
archery: 39
swordsmanship: 40
catching: 37
training: 49
fishing: 30

**Comment by Rasgnarok** [comment]
Done! We will be looking into the Martial Arts issue now, thanks for reporting \o/

**Comment by cjn213** [comment]
Thanks man
