### ISSUE TITLE
Been given starter kit whenever i disconnect at spawn

### ISSUE THREAD

**Issue by Elnathanking** [ObliqueNET/Terra#11]
![image](https://user-images.githubusercontent.com/34909373/34404902-343e0dba-ebeb-11e7-8c00-3756004a4333.png)

Disconnected to change ram and was given starter kit. Ran around, went back to spawn to heal my pokemons, server crashed and was given starter kit again

**Comment by NickImpact** [comment]
This might just be a case of improper saving, but will take a look into this

**Comment by Rasgnarok** [comment]
https://github.com/ObliqueNET/Terra/issues/12
Fairly sure it is related

**Comment by Rasgnarok** [comment]
Fixed, closing.
