### ISSUE TITLE
Pokerus Leveling Bug

### ISSUE THREAD

**Issue by GracieTheLatias** [ObliqueNET/Terra#116]
I was leveling my pokemon to lvl 75, when i reached level 75 my pokemon deleveled itself to level 74. I suspected pokerus since it likes to backtrack evs gained so i tested it on another pokerus mon, leveled it to lvl 69, then it deleveled itself to level 68

**Comment by Rasgnarok** [comment]
Please open a new ticket if the issue still happens.
