### ISSUE TITLE
Magicjohnsonn ban

### ISSUE THREAD

**Issue by magicjohnsonn** [ObliqueNET/Terra#117]
i was unrightfully banned today at an estimated time of 10 pm because my friend made a joke in chat that said i unsolicited a fight and killed him. but it was he in fact who started the fight i just hit him twice and he died. i was then instantly banned no explanation no warning ban, just straight to perma ban? for why other than this "staff" member took it upon herself to do something she solely thought was right instead of acting by law. if this were in the work force or something more serious i think they would have some kind of demotion or punishment for not following the rules and abusing their power. now i know i joke around in chat all the time but when staff members tell me something i do it and you can ask harrison because he is the one who always keeps me in line. AKA an actual good staff member who doesn't abuse power. now the abusing staff member also mentioned i stole from alpha? but i have never done that in my life and also said a reason i was banned was a joke tp to show off my base which i also didnt see in the rules? but an admin did tell me i couldn't do that after and i never did it again? all im saying is im a model citizen who takes jokes a little too far but does no harm, i am just trying to experience the adventure of pokemon and enjoy a fun time with fellow poke hunters. if you revoke this ban i promise to take it a little easier in chat

**Comment by magicjohnsonn** [comment]
and at the time of my ban the whole server was upset and agreed that my ban was unjust and had no reasoning, i dont have a screenshot but if you ask in chat the people will tell you

**Comment by GracieTheLatias** [comment]
you did steal from Alpha, but you did give back the items after a while after he told you to stopped, also you should not joke in chat about unconsentual PVP cuz i will think it is for real. i did not know you were not temp banned before, since there was a note on you that said temp for one day, you had many many warnings in chat from other staff members, and you should not need a staff member to constantly keep you in check cuz you wanna act crazy. i am sorry i permed, but your ban was lowered to three days so wait it out please.

**Comment by magicjohnsonn** [comment]
but the ban is for no reason other than you not wanting to admit you are wrong? and if something is against the rules i think it should be in the rules everything i have been corrected on has been a different reason. thats why terms and services are so long is because how many problems can arise. 20 rules arent going to clear the board of problems and thats the whole point of staff members. to moderate the chat/game hence the name moderator so you telling me that moderators are not meant to moderate really worrys me

**Comment by magicjohnsonn** [comment]
also please list the items i stole from alpha because i have never done that? its on the rules board and i follow the rules board

**Comment by GracieTheLatias** [comment]
we can't have more than 20 rules are else no one will bother reading through them all. other staff member gave you many many many warnings also Alpha told me you did give back the items a while after he told you to stop stealing.

**Comment by magicjohnsonn** [comment]
all the warnings are from different things and you definitely have me confused with someone else because i like alpha he helped me out alot

**Comment by GracieTheLatias** [comment]
mm AlphaMieZero, the helper.

**Comment by magicjohnsonn** [comment]
and i understand thats why there are only 20 rules, and i also understand thats why the staff is in place is to moderate the game thats why i dont understand why people telling me not to do different things, i have only been on here for a week so im still learning things

**Comment by magicjohnsonn** [comment]
thats why i dont understand why different staff members telling me to do all different things is against the rules*

**Comment by magicjohnsonn** [comment]
bump

**Comment by jonaleia** [comment]
After reviewing this ticket and using my prior information, you have been bending the rules and then pulling back before you technically "break" them. You have been warned multiple times, if you really need a tempban to make you shape up then that's what you will get.

**Comment by magicjohnsonn** [comment]
i was warned but i learned? i didn't break the rules as you just stated so i'm in the clear, after i learned the rules i was not a problem i have already showed mass improvement so that whole statement is invalid, the ban is over something i didnt do which is why i feel it should be lifted and i should be reimbursed for this waste of time

**Comment by magicjohnsonn** [comment]
Do not join this server staff is abusing and will ban you without any explanation and will not even work with you on anything. worst staff i have ever ran into in any form. owner seems cool though, they could eventually fix the problems with a staff attitude adjustment and more training

**Comment by magicjohnsonn** [comment]
the server owner is great ignore past messages
