### ISSUE TITLE
Kittenchocolate banned for lying

### ISSUE THREAD

**Issue by Kittenchocolate** [ObliqueNET/Terra#118]
Hello, I was banned for lying about fighting a pokemon and saying it glitched out In order to get the pokemon I wanted. This pokemon was my favorite and was NOT spawning... I had been looking for 4 days for the Nosepass and his evolution line and asking around but I had no luck. I lied to Rasgnarok and then Matt told on me. I am sorry for what I have done and I don't intend to do anything like it again. I don't feel like a permanent ban is in order for just lying about a level 16 Nosepass. Please reconsider my ban!

**Comment by Rasgnarok** [comment]
You've been unbanned, please consider that this is a second chance that won't come twice.

**Comment by Kittenchocolate** [comment]
Thanks for the reconsideration, I am very sorry
