### ISSUE TITLE
Buggy Beacon

### ISSUE THREAD

**Issue by Idylliic** [ObliqueNET/Terra#120]
First tests(Heill) 
 Testing range with the bug, the only way to get the effect is to stand  on top of the beacon base.(Blocks of minerals)
   -Even in the same chunk there is no reapplication. 
   -Tested both in and outside of a claim. 
  -Tested with same type blocks.
Max tier beacons should normally have a range of 120 blocks from the center. The range with this is about a range of 4.
Second Tests(Nyr)
Tested the range in nyr and had the same effects as the previous. 

Everything was the same. Iron blocks were the base of the beacon. The effect tested was haste 2. Using iron to pay the price. It was performed in both claimed and unclaimed land and in both of the two worlds. I placed the beacon in one chunk and not in several to see if it was just a chunk issue, and even in the same chunk there was no reapplication.

**Comment by Vohras2** [comment]
Woo fixed! Only took... several months and a reset.
