### ISSUE TITLE
I got beaned

### ISSUE THREAD

**Issue by skunkass** [ObliqueNET/Terra#121]
So I have a bit of a dilemma here, I got beaned.
Now the reasons I got banned was for pretty much being a dummy and provoking people for no reason. I can provide no proof that I won't do this again, but I will promise you my heart and soul that I will stop being such a disrespectful player on this community,

**Comment by jonaleia** [comment]
Can you explain to me what you did to get banned? Any instance that you were warned about before being banned would be appreciated.

**Comment by Rasgnarok** [comment]
@skunkass you seem to have disappeared... can you open a new ticket once you are back to life? Jona seems to have missed you by a few days and you poofed.
