### ISSUE TITLE
Quest Help

### ISSUE THREAD

**Issue by JoshyKuroiRaion** [ObliqueNET/Terra#122]
I Have spent hours trying to find Molly for the "Help at the pokecenter" quest but I can't find her it says she will be in the pokemart but for some reason I can't find  place what is called the pokemart I have asked quite a few people now and no one answers so thanks for the help server! I enjoy the server but some quests I just cant either get the quest from the quest giver or I can't find out where I am meant to go cause as I said before I can't find the place what is actually called the pokemart so pls can someone give me a pic of like the map where Molly is or maybe the coordinates just something to help. thanks for reading this and if you can help me pls do and don't ignore...

**Comment by starwarschamp4** [comment]
The pokemart in Agni is near the ice cream truck, from there look in the building.

**Comment by MattBlower** [comment]
If you read the dialogue throughout the quest, you would have seen that it says that Molly is within the Agni Pokemart, in the back rooms.
