### ISSUE TITLE
I got banned for something called pokeradar?

### ISSUE THREAD

**Issue by EvilLock** [ObliqueNET/Terra#123]
I was going around collecting master ball loot when i came across a shiny dratini. i went into a battle with it and then said in chat "I found a shiny dratini" then when i caught it i got banned. I asked ras what pokeradar was and she said its a tracking mod but the only mods i had were pixelmon optifine and a cape mod.

**Comment by jonaleia** [comment]
![hi](https://user-images.githubusercontent.com/42662545/46439960-a45cd780-c727-11e8-91d1-5e7f10b96a40.jpg)
That arrow is pointing to a hole in the ground where I had spawned a dratini. You were standing about in my position, there is no way you could have seen it. It was deep enough to where you wouldn't have been able to see it's head poking out either. Even if it's not radar, it's some sort of tracking mod and that is frankly not allowed. As well as the masterballs, one of my moderators was testing those on you in very hard-to-see places.

**Comment by EvilLock** [comment]
i made so much progress on that server then today i found out about a tracking mod but it wasnt pokeradar so i wanted to try it out, ill get rid of all the items i got from the mball loot and get rid of the shiny dratini

**Comment by jonaleia** [comment]
Alright, I will unban you under the circumstance that you remove the mod and never use anything like that again. Delete the items you are *sure* are from masterballs, don't delete anything that you might have owned. Delete the Dratini. Deal?

**Comment by EvilLock** [comment]
i love this server because of the quests, i promise ill never use anything but pixelmon and optifine of this server again

**Comment by EvilLock** [comment]
deal

**Comment by EvilLock** [comment]
im sorry and will never do it again

**Comment by EvilLock** [comment]
all the stuff i got from the mball loot is in this large chest in my room and a bit in another chest

**Comment by jonaleia** [comment]
You've been unbanned.

**Comment by EvilLock** [comment]
im sorry, i feel like im on the whole servers bad side now

**Comment by jonaleia** [comment]
Do not worry, just don't do it again.

**Comment by EvilLock** [comment]
i wont thank you so much
