### ISSUE TITLE
Banned for shitposting in chat

### ISSUE THREAD

**Issue by programmmerminecraftuser** [ObliqueNET/Terra#124]
Hey, my minecraft ign is jink144. I was recently intoxicated (you know how some nights get lolxd) and said things in chat that I shouldn't of said. I really had fun on this server and if I could be unbanned that would be cool. Thanks!

Love your Dark Elements. Love you Stabs Waifu, Love you Force Ghost Maul!

**Comment by programmmerminecraftuser** [comment]
Btw, I wasn't kidding about that 10BTC donation to own the server, but you don't have to accept. I would just like to play minecraft again with you guys!

**Comment by Rasgnarok** [comment]
Hi, looks like this issue was overlooked and lost. My apologies. Let me know if you are still around.

**Comment by Rasgnarok** [comment]
Open a new ticket and tag me in it, I'll wait!
