### ISSUE TITLE
Banned for Vulgar Language

### ISSUE THREAD

**Issue by Snowypvp** [ObliqueNET/Terra#125]
So I just logged on from a friend telling me he played and as a joke he told me to say the n word in chat and I figured oh okay nothing bad is gonna happen... something bad happened and it seems i'm banned

**Comment by Rasgnarok** [comment]
This was quite a while ago, seems it was overlooked. Are you still around?

**Comment by Snowypvp** [comment]
I am

**Comment by Rasgnarok** [comment]
Send over your username please, and we can start the process of unbanning you.

**Comment by Rasgnarok** [comment]
Open a new ticket and tag me in it, I'll wait!
