### ISSUE TITLE
Shiny Pokemon Name Color Change

### ISSUE THREAD

**Issue by StabWaifu** [ObliqueNET/Terra#128]
Can we please change the color from 'dehydrated piss yellow' to literally anything else (NOT BACK TO WHITE) that would stand out? I've seen the complaint quite a few times before, and a lot of it comes from colorblind people who really can't see the color at all, so it's not really helping in the end.

**Comment by Vohras2** [comment]
Would recommend taking this over to Pixelmon suggestion things, since Hiroku is no longer lead coder.
