### ISSUE TITLE
can's see my quests

### ISSUE THREAD

**Issue by Teadphantom** [ObliqueNET/Terra#13]
couldnt check my quests after doing the usual /quests
just wanted to check the details of my quest but this appeared
https://cdn.discordapp.com/attachments/360609493345894411/395944681910829059/unknown.png

**Comment by dualspiral** [comment]
Fixed in Sponge: https://github.com/SpongePowered/SpongeAPI/commit/f476b9de6ce3fd7606d8a5591a449e86b7edbc3a

**Comment by Rasgnarok** [comment]
Closing, fixed thanks to dual!
