### ISSUE TITLE
Xray not allowed? Wut if my Pokemon Xrays?

### ISSUE THREAD

**Issue by Bontoose** [ObliqueNET/Terra#133]
**Ok, So I mine a ton... so I'm constantly underground or in a dark place so I've fought a lot of slabeyes, anyways I noticed that if you pan your camera into a wall while in a pixelmon fight you can see through almost anything much like the Head in a leaf block trick... "honestly prolly a flaw with pixelmon or Minecraft itself" but I figured I'd tell you it's possible

Cheers**

**Comment by Vohras2** [comment]
Not sure if this is still a problem, but needs to be reported to Pixelmon if so.
