### ISSUE TITLE
Not a bug just spiders....

### ISSUE THREAD

**Issue by Bontoose** [ObliqueNET/Terra#134]
**I hate spiders.... So I've come across a fair few of the cave spider spawners and all seem to be active... now that might not be a big deal but it's in pixelmon world where mobs aren't supposed to be... It could be an over site in my opinion as spiders and Cave spiders are two different mobs... They could have also been reactivated with the generation of the mine shafts as well Idk it could be a lot of things, As far as I can tell all Cave spider spawners are active I have yet to find a default or (pig) spawner in any mineshaft

Cheers**

**Comment by Rasgnarok** [comment]
Can we confirm this on 7.0.3 with Terra's Vanha or Stratos' map?

**Comment by Vohras2** [comment]
This is an issue with sponge. Not sure there is any way for us to fix at the moment.
