### ISSUE TITLE
Kinda go banned aye

### ISSUE THREAD

**Issue by OMGitsARand** [ObliqueNET/Terra#136]
Happened like a while ago, Got banned on Terra for being rude to staff and spamming I believe. I got no proof because it was ages ago and Kayouri isnt a staff member anymore so yeah, She banned me for persistanly being obnoxious and 'toxic'. I can promise not to do it again so yeah, Cheers.

PS: I got banned from discord too so that would be much appreciated if my ban on discord could be revoked too.

**Comment by Rasgnarok** [comment]
I am missing a username please.

**Comment by OMGitsARand** [comment]
> I am missing an username please.

Fenq

Old IGN: 26HP
