### ISSUE TITLE
Trainers Way of Life Hiro

### ISSUE THREAD

**Issue by MedievalSundown** [ObliqueNET/Terra#138]
Cant battle/talk to apprentice Hiro. Starter is level 27 and evolved. Am I permanently locked out of the quest?

**Comment by Vohras2** [comment]
You need to have the 3 Pokemon you caught from the original quest (Onix, Pikachu, Magikarp) in your party and above level 10. Also, not evolved I believe.

**Comment by Rasgnarok** [comment]
Open a new ticket if the issue still happens!
