### ISSUE TITLE
Got banned for something I didn't do

### ISSUE THREAD

**Issue by IdrkAnymore** [ObliqueNET/Terra#139]
Okay, I got banned for something I didn't do and the staff didn't take proof pics either. I'd accept the ban if I actually did something to get banned for, other than that, I say no, it's not right to ban someone for something they never did, but okay.

**Comment by Rasgnarok** [comment]
Couple things missing from your ban appeal - your username, the ban reason when you try to connect, and how long ago your ban started. I literally cant tell with what you have provided so far.

**Comment by IdrkAnymore** [comment]
Ras, why did I get banned for saying phone numbers in chat when I didn't? Idek any ones irl name, how tf am I supposed to know their number when Idk their irl name and last name? Like bruh, what's wrong with you?

**Comment by Rasgnarok** [comment]
You were banned for spamming the chat with a banned player's phone number. That you have momentary Alzheimer doesn't erase that. Good of you to try, but we aren't stupid.
