### ISSUE TITLE
Ban Appeal Bunny_Love1000

### ISSUE THREAD

**Issue by Boxman1010** [ObliqueNET/Terra#146]
Stated reason: Auto Farming, Attempting to crash the server 
server: Terra 
i see everyone else ban appeal and see botnooses grinder seams to have gotten alot of people banned, all i knew was it was a good place for XP i love to play on the server id also like to mention TheBlur21 is my friends account like to say we did a joke yesterday i did not know i was banned at the time i was celebrating there birthday at there house they love to play on the server just as much as i do i do not want to be the cause of there ban reason being is because i talked using there account at there home yesterday i truly dont want to be the cause of there account being banned i did not know i was banned at the time blur can confirm with my on this. i didn't know the farm was bannable they seamed nice i dont know if it was with intent i dont believe it was i havent been on in two days and im generally confused over it but that doesnt excuse i do understand why i wont let it happen again i plan to talk with botnoose over there grinder and to figure out what happened. I do thank you to whomever reads this and for your time. i truly love to play on the server and have given some of my time to it i truly did not know it was a bannable thing i just saw a way to get XP fairly easily.

**Comment by ElementalMP** [comment]
You've been unbanned, please make sure nothing like this happens again.
