### ISSUE TITLE
Blocks aren't updating outside a set raidus.

### ISSUE THREAD

**Issue by Vohras2** [ObliqueNET/Terra#148]
Currently, furnaces, beacons, fossil revivers/cleaners and the like don't work if you aren't within a very small radius of the actual machine. It's something like 5-6 blocks total before the effects simply stop working.

**Comment by Rasgnarok** [comment]
Activation ranges are still shit outta luck

**Comment by Vohras2** [comment]
Fixed with reset, I believe.
