### ISSUE TITLE
Pure of heart wrong save point

### ISSUE THREAD

**Issue by the4bestgame** [ObliqueNET/Terra#149]
When doing the quest "pure of heart" it saves your progress after getting the medicine but before giving it to the deer. This means that if you fail the quest at any point it can't be continued, as there's no reliable way to get a full restore.

**Comment by MattBlower** [comment]
will get that re coded when I get a chance, thank you for reporting this

**Comment by MattBlower** [comment]
This has been re coded a while back, but forgot to get this closed
