### ISSUE TITLE
Quest static

### ISSUE THREAD

**Issue by Quebyn** [ObliqueNET/Terra#150]
I was doing the quest killing the tynamo, and when i killed the 10 tynamo, it says eelectross appear when i was defeating another tynamo and the game crashed. Now i cant see the quest in /quests but in the quest list it appear 25% completed

**Comment by Rasgnarok** [comment]
Still an issue?

**Comment by Quebyn** [comment]
I dont know why but 3 days later i finally can do the quest "normally"

**Comment by BlitzAsogi** [comment]
you probably got tried to be put into battle with the eelektross when you were fighting the tynamo
