### ISSUE TITLE
Statue placement

### ISSUE THREAD

**Issue by Itswhisperr** [ObliqueNET/Terra#151]
Hey, 
so Today after i was done with my ground gym battles, i rightclicked with the chisel for the statues in my hand in an admin claim. I realized that i didnt get to place any statues and i lost the statues. So apparently it just takes one away ( happened twice to me) seems like a bug to me because i think it should be restocked. 

Sincerely 
Whisperr~

**Comment by Rasgnarok** [comment]
Does it still happen? Please open a new ticket, as we changed claiming plugin and it might be solved.
