### ISSUE TITLE
mega rings lost on update to 7.0

### ISSUE THREAD

**Issue by ElementalMP** [ObliqueNET/Terra#152]
![image](https://user-images.githubusercontent.com/31155918/52170784-9bebda80-27b5-11e9-93ad-4c25b1357942.png)
On update, some users no longer have mega rings, as shown.
Users are still tagged with having the ring serverside, and so it cannot be returned via commands or by defeating a boss
Update: After more testing, mega evolution works outside battle, but not during battle.

**Comment by Rasgnarok** [comment]
Fixed for 7.0.1
