### ISSUE TITLE
All Alone in Savanna Biome...

### ISSUE THREAD

**Issue by Bontoose** [ObliqueNET/Terra#154]
As far as I can tell nothing is spawning in Savanna's after the 7.0 update...I've checked out multiple savanna biomes and all of them don't spawn a single pokemon... also I saw poochyena's being spawned in a birch forest which is usually only found in savanna's

Edit: you can add Jungle Biomes to the list

**Comment by Rasgnarok** [comment]
Fixed for 7.0.1
