### ISSUE TITLE
Battle rules broken if in a battle on server shutdown.

### ISSUE THREAD

**Issue by ElementalMP** [ObliqueNET/Terra#158]
If the server goes down during a battle that used battle rules, this screen will come up upon joining every time
![image](https://user-images.githubusercontent.com/31155918/52171151-a9f12980-27bc-11e9-9035-fb2f4828ff76.png)

**Comment by Rasgnarok** [comment]
This should be forwarded to https://www.pixelmonmod.com/tracker.php?p=2 with updated information!

**Comment by Vohras2** [comment]
Closing. Please forward to Pixelmon if still an issue.
