### ISSUE TITLE
Can't see the name of other player's pokemon

### ISSUE THREAD

**Issue by GodNoct** [ObliqueNET/Terra#161]
Whenever I am next to someone who is battling or just have their pokemon out, I cannot see their pokemon's owner name. My wife could not see mine but i could see my own's, and I could not see hers, but she could see her pokemon's owner.    
I.E.
[GodNoct]    <--- This is what she cant see but i can, my name on my pokemon.
Mimikyu
lvl: 28

**Comment by Rasgnarok** [comment]
Forwarded to the devs

**Comment by Vohras2** [comment]
Closing since forwarded to Pixelmon.
