### ISSUE TITLE
[SUGGESTION] Make Roles in the Team Plugin

### ISSUE THREAD

**Issue by FishyFisho** [ObliqueNET/Terra#169]
Have executives and ranks in the teams so it becomes easier to invite players etc, maybe even set the team home.

**Comment by Rasgnarok** [comment]
How far do we want to go? Do we want to include some make-up perms, kicking, setting home and etc? I'd love to see a discussion on this.

**Comment by FishyFisho** [comment]
If we were to rank members in the team by:
-Leader
-Executives
-Grunt
And that the leader of the team, could set up the perms for each rank in a GUI menu.

**Comment by Vohras2** [comment]
Closing this since it has been denied. Would make the team plugin too similar to towns on Stratos.
