### ISSUE TITLE
[7.0.1] NPE at hiroku.quests.listeners.PixelmonHandler.lambda$onBattleStart 

### ISSUE THREAD

**Issue by Vohras2** [ObliqueNET/Terra#170]
https://gist.github.com/Vohras2/2c31cccb7212d2222a4b3c328dc84334

**Comment by Rasgnarok** [comment]
Should check if this still happens at all.

**Comment by Vohras2** [comment]
This still happens. https://gist.github.com/Vohras2/dc6e662fbd4bc5205139d5cdda192192

**Comment by Vohras2** [comment]
Closing for now since sent to Hiroku
