### ISSUE TITLE
[7.0.1] ClassCastException at pixelmon.comm.packetHandlers.ExecuteExternalMove$Handler on EntityItemFrame

### ISSUE THREAD

**Issue by Vohras2** [ObliqueNET/Terra#173]
https://gist.github.com/Vohras2/7bfd9b0dbb6f3b483793508d3bc22e04

**Comment by Rasgnarok** [comment]
This needs to be forwarded to Pixelmon, probably not fixed as of 7.0.3.

**Comment by Rasgnarok** [comment]
https://www.pixelmonmod.com/tracker.php?p=2&t=13440

**Comment by Rasgnarok** [comment]
@Vohras testing
