### ISSUE TITLE
[674 GP] NPE at ryanhamshire.griefprevention.command.CommandTrust.execute

### ISSUE THREAD

**Issue by Vohras2** [ObliqueNET/Terra#174]
https://gist.github.com/Vohras2/3dd3dcab63a99c61a2d44b5d15bbef1b

**Comment by Rasgnarok** [comment]
Tab complete error, likely linked to the ones we see with economylite. Needs to be retested on the current versions.

**Comment by MattBlower** [comment]
guessing this GP one can close seeing as we dont use it no more :P

**Comment by Vohras2** [comment]
Closing since it is GP.
