### ISSUE TITLE
[7.0.1] NPE at npcs.registry.DropItemRegistry.getDropsForPokemon

### ISSUE THREAD

**Issue by Vohras2** [ObliqueNET/Terra#177]
https://gist.github.com/Vohras2/0bf8aa0096385c88491c649d8f1627c1

**Comment by Rasgnarok** [comment]
Won't forward it until I see it happen again on 7.0.3.

**Comment by Rasgnarok** [comment]
Linking these two together, as they are related to faulty trainer jsons: https://github.com/ObliqueNET/Terra/issues/176. Same condition applies.

**Comment by Rasgnarok** [comment]
Yet another related issue, https://github.com/ObliqueNET/Terra/issues/171

**Comment by Vohras2** [comment]
Closed, since I think this is fixed.
