### ISSUE TITLE
[Error Log] ArrayIndexOutOfBoundsException at pixelmon.api.storage.PartyStorage.get

### ISSUE THREAD

**Issue by Vohras2** [ObliqueNET/Terra#184]
https://gist.github.com/Vohras2/178f242f2438a27ec9dc2c89d2a1976b

**Comment by Rasgnarok** [comment]
Forwarded.

**Comment by Rasgnarok** [comment]
Forwarded https://www.pixelmonmod.com/tracker.php?p=2&t=13331
