### ISSUE TITLE
Admin claims + frost walker spams chat

### ISSUE THREAD

**Issue by TheTunzo** [ObliqueNET/Terra#194]
![2019-02-21_01 46 17](https://user-images.githubusercontent.com/45803292/53136830-c1802e80-3580-11e9-868f-042ab08a67a3.png)
Walking next to water with frost walker boots in an admin claim causes a massive spam of error messages as you can see in the screenshot. These messages cover about 3/4 of all visible chat messages and they all appear instantaneously. New error messages won't appear unless you exist the "near water" area and re-enter it.

**Comment by Vohras2** [comment]
Fixed, so closing.
