### ISSUE TITLE
Frillish/Jellicent texture bug and Apricorn trees

### ISSUE THREAD

**Issue by Hunter1220** [ObliqueNET/Terra#2]
The Apricorn tree model has been updated but it would appear that the old model still exists in the game and is currently bugged. It lacks textures making it essentially an indestructible 1x2 barrier block. In regards to the Frillish texture bug, here's an image as to what it looked like in game for me. [https://puu.sh/yOv89/576b9937a3.png](url)
I don't have a screenshot for Jellicent but they seemed off as well so I'd check them.

**Comment by Rasgnarok** [comment]
The link isn't working for me, but I can assume you mean it is invisible. I saw it on the discord as well, so I know this is a legit bug - it'll have to be reported back to the mod authors. I'll keep it open until I follow up with them and make sure it is sorted!

**Comment by Hunter1220** [comment]
Just as an update by the way, the male version actually uses the wrong model. It's using the female model.

**Comment by Rasgnarok** [comment]
Closing, fixed for next update.
