### ISSUE TITLE
RPG Exp glitch

### ISSUE THREAD

**Issue by Vohras2** [ObliqueNET/Terra#201]
Had a player tell me that they had something spam that they caught a mon several times over, giving them tons of increased rpg experience. The mon in question also received a lot of experience, but it stayed at lvl1 and didn't level. They used a rare candy on it, and it shot up to level 52.

**Comment by Rasgnarok** [comment]
Probably related to https://github.com/ObliqueNET/Stratos/issues/75, closing in favour of that one.

**Comment by fatyg5** [comment]
I imagine this is fixed and can be closed, was referenced over on Stratos and I've closed that.
