### ISSUE TITLE
Some mistakes are too big...

### ISSUE THREAD

**Issue by samuelwagamanlewis** [ObliqueNET/Terra#203]
So, a fortnight ago, my brother, Flavius, decided it would be comical to type the N- word (which is demeaning nomenclature towards our fellow brothers from Africa) in Oblique's Pixelmon Reforged Server. From this mistake, I learned to never leave my computer unattended because Flavius is ready to pounce upon the opportunity. I hope you can understand, please grant thy mercy upon a brother and #FREEKINGSNAKE411

**Comment by samuelwagamanlewis** [comment]
> So, a fortnight ago, my brother, Flavius, decided it would be comical to type the N- word (which is a demeaning word towards our fellow brothers from Africa) in Oblique's Pixelmon Reforged Server. From this mistake, learned to never leave my computer unattended because Flavius is ready to pounce upon the opportunity. I hope you can understand, please grant thy mercy upon a brother and #FREEKINGSNAKE411

**Comment by JosephineWagamonLewis** [comment]
wow brother this was heartfelt, i really hope a brudda gets unbanned as you now clearly understand that Flavius cannot be trusted. The tribes in the homeland send their support.

**Comment by samuelwagamanlewis** [comment]
https://www.lifehack.org/articles/communication/10-famous-failures-that-will-inspire-you-success.html

**Comment by ElementalMP** [comment]
Can I get an IGN?

**Comment by samuelwagamanlewis** [comment]
me llamo kingsnake411

**Comment by ElementalMP** [comment]
I've revoked your ban, this is your last chance. Please ensure this doesn't happen again.

**Comment by samuelwagamanlewis** [comment]
My life is yours now

**Comment by FlaviusWagamusLewis** [comment]
Thank you sir, I will atone for my sins and support the brothers in Africa. It was my honest mistake, thank you for your kind soul.
