### ISSUE TITLE
Flying-Poison Badge

### ISSUE THREAD

**Issue by Dj4874** [ObliqueNET/Terra#204]
A few weeks ago, before the update, I challenged The Tunzo to a gym battle in the Flying gym. I got my ass kicked, but Tunzo put in the victory command for me instead of him. So it registered as me beating the gym and I got all of the rewards. I wanted to actually beat the gym, so I gave the stuff back. I just beat the new Flying-Poison gym and now the command won't give me the stuff back, as it says I have already beaten it. I beat Rocker113 or Ross in the flying poison gym.

**Comment by FishyFisho** [comment]
The original Flying Gym turned into Dragon/Steel so that isn’t a issue I believe.

**Comment by Dj4874** [comment]
Well, the issue is that I don't have the flying gym rewards, because I handed everything back in.

**Comment by Owski2002** [comment]
DJ did you ever defeat the Psychic gym?

**Comment by Dj4874** [comment]
Yeah, I did.

**Comment by Vohras2** [comment]
I explained this to him in game, about how the Flying gym is now Dragon/Steel. I left a note about him being allowed to rechallenge the 8th gym after Tunzo gave him the win by mistake. Should all be sorted out and can be closed.
