### ISSUE TITLE
XP Bug

### ISSUE THREAD

**Issue by ShadeDrezin** [ObliqueNET/Terra#205]
There's a bug that causes dramatic xp gains. The player seems to get stuck in the battle screen where it says what poke gained xp and this causes pokemon to jump from lower levels to near max. As far as I know its happened to Rogue_B and IH8Registering.

**Comment by Vohras2** [comment]
Someone captured a video. https://youtu.be/Ub0jqoJ9e3s

**Comment by Vohras2** [comment]
Fixed.
