### ISSUE TITLE
World spawn location not set properly.

### ISSUE THREAD

**Issue by ElementalMP** [ObliqueNET/Terra#206]
New players aren't spawning properly in the world. They end up on pillars around spawn, where they cannot get down without death. This has happened with everyone that joins, without fail.

**Comment by Vohras2** [comment]
I think you should have the ability to /setworldspawn, shouldn't you, Ele?

**Comment by ElementalMP** [comment]
I do, but if it is a problem with sponge it needs to be documented~

**Comment by Rasgnarok** [comment]
It's the world spawn radius gamerule not working correctly

**Comment by Vohras2** [comment]
Wooo Ele fixed.
