### ISSUE TITLE
Exp Boosters not working with XP Share and XP All

### ISSUE THREAD

**Issue by Vohras2** [ObliqueNET/Terra#208]
Currently, RPG boosters aren't working correctly and distributing the increased xp to the other mons.

**Comment by Vohras2** [comment]
Bug on Pixelmon end, so closing.

**Comment by MattBlower** [comment]
So this means paid boosters are pretty much not going to work properly again?

**Comment by Vohras2** [comment]
It's on Pixelmon's side. Nothing we can do about it.

**Comment by MattBlower** [comment]
so there is no real point buying the higher ranks now due to the no boosters, so would the ranks be reworked?

**Comment by Vohras2** [comment]
You still have access to the higher tier boosters. They just aren't able to be spread across the whole party. It is still a benefit to leveling up, and the RPG boosters are completely unaffected. However, that is up for Ras to decide.

**Comment by MattBlower** [comment]
its not just EXP Share/All though, switch training is also broken. It only affects the active pokemon at the end of the battle so it really isnt faster
