### ISSUE TITLE
Professor Ras not inspecting my Pokemon

### ISSUE THREAD

**Issue by TulioKy** [ObliqueNET/Terra#209]
In the quest "Trainer's Way of Life", I caught all three Pokemon and talked to her, but her dialog box doesn't change and the quest doesn't continue. Is it because I evolved my Magikarp into a Gyarados?

**Comment by Vohras2** [comment]
Yes, that would do it. It needs to be a magikarp. You also need to have all 3 in your party when you speak to her.
