### ISSUE TITLE
Logging in after being kick from AFK in battle counts you still being in battle

### ISSUE THREAD

**Issue by BlitzAsogi** [ObliqueNET/Terra#21]
![image](https://user-images.githubusercontent.com/24644181/34476480-15820b08-efcc-11e7-9bfd-190bfa68656d.png)

**Comment by DeathVirus** [comment]
If you're still stuck like that, from what I remember, starting a battle with another mon will get you out of that.

**Comment by Rasgnarok** [comment]
Closing issue because AFK has been kicked out
