### ISSUE TITLE
Ping issues

### ISSUE THREAD

**Issue by TrustTrost** [ObliqueNET/Terra#211]
My friends and i have started playing pixelmon but i cant really do anything on your server because for some reason i got a ton of lag. Normally my ping is pretty good and i rarely lag at all but when i'm on you server i just lag. I went on a different server and my ping was fine, i did a solo pixelmon world and my ping was fine, but when i went onto your server it was terrible. I'm always rubber banding, my Pokemon never come out and i'm falling through the earth. If there is any thing you can do to help that would be good

**Comment by Vohras2** [comment]
It's quite possible there is something interfering between your home location and the server host.

**Comment by TrustTrost** [comment]
Probably. Hopefully one day it just magically fixes its self. This is probably unrelated but normally when i'm playing multiplayer games i tend to be auto connected to Asian servers for some reason

**Comment by Rasgnarok** [comment]
Well the host isn't in Asia, and we don't have multi-server connections. It's in Canada. I'd need to see a mtr trace on your end, or even pinging the IP to see what happens.
