### ISSUE TITLE
[Suggestion] Shadow Crate

### ISSUE THREAD

**Issue by PrimalCyndaquil** [ObliqueNET/Terra#212]
--- Shadow Crates, Pokémon and Quests. ---

Similar to the Crazy Critters, Shadow Pokémon would be unique, odd pokémon exclusive to the Shadow Crate item. Each shadow pokemon would have a dark-grey name and smokey/purple particles flowing around them. As shadow pokémon were originally created by the evil team in Pokémon Colosseum, the method of obtaining a Shadow Crate could be through a long, chaptered quest line in which the player would receive a few keys as they progress through it. In order to complete their collection, players may then purchase a Dull Shadow Crate for 2500, that works in a similar way to the Crazy Crate in which you'd have a chance of getting a regular ol' head or a token redeemable for a regular Shadow Crate.

Shadow Pokémon would be OU, not allowed in gym battles and feature exclusive moves/abilities otherwise unobtainable through normal means.
Here are some suggestions for particular shadow pokémon:

Shadow Lucario with Skill-Link and Arm-Thrust.
Shadow Togekiss with Prankster and Celebrate.
Shadow Metagross with Technician and Iron Head.
Shadow Ampharos with No-Guard and Zap Cannon.
Shadow Smeargle with Prankster and Baton Pass.
Shadow Shuckle with Stamina and Reflect.
Shadow Alolan-Ninetales with Magic Bounce and Aurora Veil.
Shadow Delcatty with Wonder Guard and Wish.
Shadow Roserade with Merciless and Toxic Thread.
Shadow Alolan-Persian with Fluffy and Night Daze.
Shadow Lugia with Corrosive and Shadow Force. (Rarest of the bunch, plus Ubers.)

**Comment by Vohras2** [comment]
Don't think this will ever be a thing. The Crazy Crate is implemented because they are balanced and heavily debated. The suggestions here are both broken and unnecessary. We also don't need another crate that simply competes with the Crazy Crate. It would be better to implement any new such mons through it.

**Comment by Rasgnarok** [comment]
Shadow pokémon are actually planned by the mod too, so it's not necessary to do this. If this is ever added, it would be a cosmetic difference via texture pack (because we can't add visuals like new textures without tampering the client).
