### ISSUE TITLE
Shields Down Blocking Substitute

### ISSUE THREAD

**Issue by Hunter1220** [ObliqueNET/Terra#213]
For some odd reason, Shields Down appears to be stopping Substitute from going up. I am unsure if this affects any other moves but I know it at least affects this one. https://puu.sh/D1qqm/ccd78eb218.gif
Notice how when Shields Down is still active that nothing happens when Substitute is used, however, once Shields Down is inactive Substitute works like normal.

**Comment by Rasgnarok** [comment]
Please report to the Pixelmon mod directly: https://pixelmonmod.com/tracker.php?p=2
