### ISSUE TITLE
Seems like the server is not letting me join

### ISSUE THREAD

**Issue by TulioKy** [ObliqueNET/Terra#214]
It started out yesterday when I tried to play on the server again, it just spends on the "Logging in" phase before saying "Connection lost" along with "Disconnected". I tried every which way to fix the issue, but nothing worked so far.

If anyone sees me online, I'm not actually online, it's Minecraft thinking that I'm online. So if anyone can tell me how to fix the problem, I'll greatly appreciate that.

**Comment by Rasgnarok** [comment]
Does it work now?
