### ISSUE TITLE
My Pokemon faint when I click on them

### ISSUE THREAD

**Issue by TulioKy** [ObliqueNET/Terra#215]
After one of my Pokemon legitimately fainted, the next one I clicked to send out instantly fainted despite not there being any influence from the opposing Pokemon. None of my Pokemon were poisoned or burned nor Stealth Rocks were in place, no Perish Song or the Ghost-type Curse.

Update: Seems like I didn't encounter this bug again, but since it isn't showing up on Pixelmon's own changelog, I will keep it open just in case someone else runs into this bug.

**Comment by Rasgnarok** [comment]
Can you please report it to the Pixelmon mod directly: https://pixelmonmod.com/tracker.php?p=2
