### ISSUE TITLE
Fighting Gym Stage Not Working

### ISSUE THREAD

**Issue by MrMoMo13** [ObliqueNET/Terra#216]
the fighting gym arena has been "broken" for quite a while now and as a fighting leader its sometimes frustrating to have to tell every challenger to go fight outside stage is broken or go fight out here, and I just feel like fixing it just makes it easier for anybody because it is annoying not having your gym work. Anyways no rush but I do hope it gets fixed.

**Comment by Kitsune30** [comment]
Can you describe what happens?

Does the pokeball get thrown out and then the pokemon not actually appear?
If so I can probably have it fixed by tonight.

**Comment by MrMoMo13** [comment]
Yes that is what happens

**Comment by MrMoMo13** [comment]
sorry for the very late reply

**Comment by Vohras2** [comment]
Looks like this has been fixed.
