### ISSUE TITLE
Crazy Crate Pokemon not persisting after server restart

### ISSUE THREAD

**Issue by Shika-The-Deer** [ObliqueNET/Terra#217]
When the server restarts such as to fix lag issues or update a plugin, the Pokemon with special abilities/moves from the Crazy Crates disappear or turn into level -1 Bulbasaurs. Edit: If the server resets a second time, the Pokemon come back but without their edited abilities.

**Comment by Rocker113** [comment]
This is what happened to me on this:
1. Joined back after the restartwith the crazy crate mon missing from its slot in my party
2. Left and rejoined a lil bit later after swapping out 4/5 of the other slots with eggs
3. The empty slot that had been the mon had turned into a level -1 fainted bulbasaur
4. After the second restart the bulbasaur was replaced with the original crazy crate mon but with the normal abilitity.

**Comment by Vohras2** [comment]
Pixelmon side problem. Nothing we can do about this at this point.
