### ISSUE TITLE
Suggestion: /TcToggle

### ISSUE THREAD

**Issue by SaintGearz** [ObliqueNET/Terra#218]
Adding the command so team members can use /tctoggle, allowing members to toggle the /tc command. This allows players to continuously communicate with fellow mates! Btw ras told me to come here <3
![Screenshot_3](https://user-images.githubusercontent.com/7758287/55019113-7c04b600-4fb1-11e9-8b5b-1baa0e9ada0a.png)

**Comment by Vohras2** [comment]
Should be in after next restart.
