### ISSUE TITLE
#Quest issue: Enter The Dojo

### ISSUE THREAD

**Issue by Maxs1301** [ObliqueNET/Terra#22]
I was doing the quest: Enter the dojo(stage: Enter the cave), when i ran into a problem. After doing the 3 things he said and speaking with him he said he would give me a note or coords or something, Unfortunately i didnt get the coords or something. 
The hint is: You really need a hint?
A friend of me did the same quest and is also stuck on this point. Do we have to found the cave and is this hint after that available, or is this maybe bugged? He said he would contact me with Azelf.

Greetings Maxs1301

**Comment by Soshisen** [comment]
Fixed. Players already on this art of the quest were also given the item they were missing
