### ISSUE TITLE
Claim Issues

### ISSUE THREAD

**Issue by nbrandon287** [ObliqueNET/Terra#221]
/abandonallclaims isn't working.

As an new user I claimed a chunk yesterday, and before I set a home teleported away a few times. I know this is my fault, but now I don't know where my claimed chunk is and I can't claim any more land because it's not adjacent to it. 

Is it possible to get the command working or remove my claim?

IGN: Zaronto

**Comment by MattBlower** [comment]
Do /base to warp to it

**Comment by nbrandon287** [comment]
Amazing, thank you so much.
