### ISSUE TITLE
Accidental Copy Paste

### ISSUE THREAD

**Issue by 9Yinn** [ObliqueNET/Terra#222]
I accidentally pasted something on the Oblique Terra server and it was advertisement which I didn't mean to send because I didn't know I had it pasted and I got banned because I accidentally sent it in the chat, can I please get unbanned? Sorry for the trouble.

**Comment by ElementalMP** [comment]
Hi there. I've looked over this appeal, and due to the fact you were playing on Oblique before this, I will give you the benefit of the doubt. I've unbanned you, but please do be more careful in future.

**Comment by 9Yinn** [comment]
I am still banned on the server, my in game name is 9Yin. Maybe you unbanned the wrong person? Sorry for everything and thank you for your time.
