### ISSUE TITLE
so like I got banned for saying the n word in a private command

### ISSUE THREAD

**Issue by duckywam** [ObliqueNET/Terra#224]
yea I did /trust nigger as a joke cause I was screen sharing with a mate and didnt realize that It would be seen and aswell as that I didnt think anybody would care but turns out **_the auto moderator doesnt like that _** ### but anyway can I get unbanned lol (also my username is emerald_lord)

**Comment by Rasgnarok** [comment]
That's definitely hilarious, don't get me wrong. Of course we would have an autobanner for that kind of language, considering what the word _is_, but still amusing it catches commands like that. I'll unban you, but know that type of language is moderated.
