### ISSUE TITLE
Ban Appeal - Gryphmo

### ISSUE THREAD

**Issue by Gryphmo** [ObliqueNET/Terra#226]
I would like to make a ban appeal. Some time ago i got banned in both the Minecraft server and Discord channel. I dont remember exactly what i did, but i think i didnt behave well against the staff members and i acted like a douche. What i do know is that i did all those things just to get banned because i had a problem with spending too much money on donations etc. After i got banned i didnt have anything really to spend my money on and it helped me "fix" my problem, not fixed yet but im getting there. So i would like to apologize to whoever i was a douche against and i wont do this again. I really liked the server and the other playes, so i hope i will get a second chance.

Discord: Gryphmo #1112    Minecraft: Gryphmo

**Comment by Rasgnarok** [comment]
I can always unban you, but it'll have to be on the condition I block you from donations - since it seems that the crux of the issue lies in how we offer services you abuse of, and you act out against us when it gets overwhelming.

**Comment by Gryphmo** [comment]
That is okay :)

**Comment by Rasgnarok** [comment]
You are now unbanned (and banned from the store). If you ever feel like quitting, remember I gave you a second chance and I'd rather you DM me about it.
