### ISSUE TITLE
Quilladin Lost in Waiting

### ISSUE THREAD

**Issue by Raundre** [ObliqueNET/Terra#227]
![Untitled](https://user-images.githubusercontent.com/49658502/56161499-839af780-5f7e-11e9-8209-d2c493893d7d.png)

Raundre here! As shown in the attached image, I encountered a Quilladin and then got stuck on a waiting dialogue box (after throwing a few Poke Balls). Let me know what else is needed to get back into the encounter, as I haven't reported this before. Thanks!

**Comment by Rasgnarok** [comment]
BlitzAsogi will be spawning one in for ya!
