### ISSUE TITLE
Temporary Duplication Glitch

### ISSUE THREAD

**Issue by Blitzmentalist** [ObliqueNET/Terra#228]
Has occurred to both myself (Ign: BlitzMentalist) and user Zendicoo.

Moving items in inventory will create duplicates of the item in the prior slot. These duplicates can be interacted with and stacked with the prior versions, but interacting with them again later usually causes them to disappear. Likely caused due to client side lag, as mods viewing inventory show no duplicates.

**Comment by Vohras2** [comment]
This has been forwarded to Pixelmon. Closing for now.
