### ISSUE TITLE
Quest Bugs

### ISSUE THREAD

**Issue by nbrandon287** [ObliqueNET/Terra#229]
New in Town: Stuck on Talk to the Storekeeper, neither of the shopkeeps will progress the quest.

The Steel Curtain: Talking to Andy wont progress the quest. (I even made sure I had the iron block in hand)

IGN: Zaronto

**Comment by starwarschamp4** [comment]
Andy needed a new ID, will be fixed soon. New in town will also be fixed. Thanks for the help.

**Comment by nbrandon287** [comment]
Both of these seem to have been resolved so I'm going to close this.
