### ISSUE TITLE
Mob exp bug

### ISSUE THREAD

**Issue by GracieTheLatias** [ObliqueNET/Terra#230]
Endermen in the End do not give exp after killing them, i rtp'd far away from an admiin claim so that is not the issue. Pigmen in the Nether are also having the same issue.

**Comment by Vohras2** [comment]
This is because the doMobLoot gamerule is off. It stops them from dropping their standard drops, including xp.

**Comment by Vohras2** [comment]
Was wrong. Was mobs not having correct ID in RPG. Roku fixed.
