### ISSUE TITLE
Quest: Flute of the Pure Note issue

### ISSUE THREAD

**Issue by nbrandon287** [ObliqueNET/Terra#231]
I'm stuck on the Head to the Bastion in Heill step. I'm not sure if I just can't find the trigger or it doesn't exist. I walked nearly every block between spawn and the heill portal, went all through the Bastion, talked to every npc in the Bastion.

IGN: Zaronto

**Comment by starwarschamp4** [comment]
Needs fixed due to new Bastion location

**Comment by nbrandon287** [comment]
Quest is fixed.
