### ISSUE TITLE
Multiple Quests Issues

### ISSUE THREAD

**Issue by nbrandon287** [ObliqueNET/Terra#232]
Poison Point: I think no trigger for the 'Head to the Witch Village in Bastion'. I'm guessing because of the bastion move.

Where the Grass is Greener CH1: Is now back in my quest log, but I can't talk to Wilda to finish it. She just gives her generic chat line.

If the Bastion quests are going to be a while before they are fixed could I have Poison Point and Flute of the Pure Note reset and removed from my log? Thanks!

**Comment by starwarschamp4** [comment]
These are being looked into and worked on as soon as possible. Leave your ign for them to be reset.

**Comment by nbrandon287** [comment]
Of course.. this is the ticket I forgot to leave my IGN.

IGN: Zaronto

**Comment by Th354ndman** [comment]
All these issues have been fixed.
