### ISSUE TITLE
Ultra Space wormholes do not appear to spawn

### ISSUE THREAD

**Issue by Smurfsrulle** [ObliqueNET/Terra#235]
It's been about 2 weeks since the server reset and as of yet nobody (that I'm aware of, having spoken to a lot of players including staff members) appears to have been in ultra space. That leads me to believe that ultra space wormholes don't spawn in at all, since despite them being a rare spawn, we should have seen players there by now with 70+ people online constantly.

Even testing /checkspawns in single player the chances are around 1/500-1/2000 or so of them spawning depending on location. Rare, but not that rare (granted, the spawn rate could have been adjusted for this server).

Someone else was meant to report this issue yesterday but having not seen it posted, I'll do the honors. I'd be glad to be proven wrong.

**Comment by Vohras2** [comment]
We are currently working on something to fix this.
