### ISSUE TITLE
Ban appeal for Cruxalux

### ISSUE THREAD

**Issue by Cruxalux** [ObliqueNET/Terra#237]
I got really heated at someone who kept killing me out of nowhere at spawn, and I called him a faggot in chat which got me autobanned. Id like to get it appealed and also get help with turning off pvp so I don't have to deal with people doing that.

**Comment by ElementalMP** [comment]
Hi there! I've read this over, and revoked your ban. Please not that this kind of language is not tolerated, and second chances do not come by often! As for the PVP, as far as I know it's WIP, and should be fixed soon.
