### ISSUE TITLE
Bastion Quest npc's

### ISSUE THREAD

**Issue by dshannon519** [ObliqueNET/Terra#240]
Jean-Claude: Iron Maiden trigger point

General Angin: War effort trigger point

Captain Mason: The fire beast trigger point

**Comment by starwarschamp4** [comment]
The quest team know of the Bastion ID issues for the npcs and one will get to fixing them soon. Also, there is a witch village for the quest in the new Bastion, just needs editing for the quest.

**Comment by Th354ndman** [comment]
This issue has been fixed.
