### ISSUE TITLE
Quest Bug: Trials of a Magma Storm

### ISSUE THREAD

**Issue by nbrandon287** [ObliqueNET/Terra#242]
Volcanion didn't/doesn't spawn for the Defeat Volcanion step.

Looks like someone else in the discord support channel is having the same problem.

IGN: Zaronto

**Comment by nbrandon287** [comment]
The quest was rolled back.. because of a reupload?

Now I have a step I didn't have before, to kill 3 different types of pokemon. I can't get into that room though. I went back to the hole and it doesn't teleport me.

**Comment by MattBlower** [comment]
This can be closed as quest is now working. If you still cannot progress the quest due to the reupload then please comment in support
