### ISSUE TITLE
[Quest Issue] Way of the Gym Typo

### ISSUE THREAD

**Issue by PrimalCyndaquil** [ObliqueNET/Terra#243]
Couple of issues here some helpful buds pointed out:
IcedYoda pointed out that there's a pretty big typo in the Way of the Gym rewards. The sp def power item's description instead details how it grants Speed EVs.

Disregard this last one, seems it was just a thing that they were in the middle of the quest when it Updated and they just had to restart some of it. Sorry!
_Isuckatgames also seems to be stuck at Stage 9 of the quest "Flute of the Pure Note" despite having collected the correct item for it. The white iron was obtained but Booth doesn't seem to want to move the quest forwards. After restarting the quest, the glitch seemed to go away._

**Comment by Vohras2** [comment]
Closing, since WOTG type was fixed.
