### ISSUE TITLE
[Bane Appeal] I used to play on Terra, took a month break from public servers -- logged in saw I was banned?

### ISSUE THREAD

**Issue by maddimoonlight** [ObliqueNET/Terra#244]
It said Reason: Advertising Oblique.

I don't remember really advertising on Oblique at all, I am a big solo player and not a big talker so I don't see why I would be advertising. Curious if my account was compromised or something because of this. Or if I was advertising Oblique.... Where? When? 

Just some evidence supporting this ban would be respectful at least, seeing as I'm totally in the dark and just looking to catch some 'mons.

**Comment by Owski2002** [comment]
We are going to need to know what your ign is. So we can find this evidence.

**Comment by maddimoonlight** [comment]
Maddimoonlight

**Comment by maddimoonlight** [comment]
Same as my username. :)

**Comment by Rasgnarok** [comment]
Can you please give me your discord username as well?

**Comment by maddimoonlight** [comment]
My discord username is #8137

**Comment by maddimoonlight** [comment]
Sorry for the late reply, forgot about this.

**Comment by maddimoonlight** [comment]
Bump for this to get noticed.

**Comment by Rasgnarok** [comment]
No need to bump, I receive emails for all tickets. Your discord username is not numbers, its, for example, @Rasgnarok#6969. I need the full thing, or you canDM me directly on Oblique's discord.

**Comment by Vohras2** [comment]
Going to close this since the OP hasn't responded in 2 months. Feel free to reopen and refer back to this issue if you still feel you were unjustly banned.
