### ISSUE TITLE
A Blank Mind missing kit

### ISSUE THREAD

**Issue by BlitzAsogi** [ObliqueNET/Terra#245]
![image](https://user-images.githubusercontent.com/24644181/56845533-6eff1d80-68f5-11e9-87ff-493061a8ffb1.png)
Kit ABM at stage 10 of "A Pure Mind" is missing from the list

**Comment by BlitzAsogi** [comment]
For whoever fixes this, stage 12 directs the player to the heillportal to catch an onix, but they dont spawn there anymore. They now spawn in spiral cave

**Comment by Th354ndman** [comment]
Both of these issues have been fixed.
