### ISSUE TITLE
Quest Bosses

### ISSUE THREAD

**Issue by Kayouri** [ObliqueNET/Terra#248]
Not sure if it's intended, but when doing the Mining Quest one in Agni, I got sent back to the pokecenter to heal, then after I healed, instantly got re-attacked by the Sableye before I could g et back to the cave.

Same thing happened with the Octillery with Lost at Sea, and me doing /home to heal. It followed me home to attack me, not in the cave with the sailor.
http://prntscr.com/nik0pq

**Comment by Vohras2** [comment]
Closing this for now since I haven't heard any reports about this in the last bit. Re-open if it happens again.
