### ISSUE TITLE
Quest Issue: As the Ocean Roars

### ISSUE THREAD

**Issue by nbrandon287** [ObliqueNET/Terra#249]
I believe the rendezvous point note at the end of the quest has the wrong coordinates on it. I can't figure out where to go.

The note takes you here:
https://i.imgur.com/edYQV7X.png

There's nothing there and doesn't line up with the quest text following the catch of Kyogre.

**Comment by CenizaRey** [comment]
Ay ay ay, sorry. Prior to the map reset there was something here but it seems it was removed. I'll update this ASAP

**Comment by BlitzAsogi** [comment]
Might want to double check if you input the right cords, i helped sandy fix some parts of the quest a day or so ago, and the dude was there. Went back to the cords and double checked, and he's still there. Only issue was the few NPCs behind him were wiped in the reset.
![image](https://user-images.githubusercontent.com/24644181/57052540-8d309900-6cba-11e9-86fb-14c23df116ec.png)

**Comment by nbrandon287** [comment]
The coordinates on the paper I got aren't where you are. I'll try there though.

![image](https://user-images.githubusercontent.com/25235322/57052858-f3380480-6c57-11e9-829b-eb5da5705f9a.png)

**Comment by Th354ndman** [comment]
This issue has been fixed, and can now be closed.
