### ISSUE TITLE
Trial of Magma Storm

### ISSUE THREAD

**Issue by dshannon519** [ObliqueNET/Terra#251]
When you go initially into the room, it shortcuts you using steelix straight to the volcanion step, but doesn't actually spawn the boss, /endbattle or otherwise losing a fight takes you back to the defeating the three pokemon, however, killing those pokemon seems very broken, where killing one scratches out the other of the quest page but it never seems to actually progress you, esp when all somehow get scratched out, in one case the quest straight up vanished from the book till I warped out of the volc

**Comment by MattBlower** [comment]
can be closed as is fixed
