### ISSUE TITLE
Quests randomly delete from "active quests" but still show as active in view quests

### ISSUE THREAD

**Issue by Noqxious** [ObliqueNET/Terra#252]
sometimes on completing/failing a quest step the quest will be removed from the active quests list but still show up in view quests as currently active.
-normally u can just ask a qd to roll u back a step and it seems to fix it, but ElementalMP refused to roll me back a step until i made  a github about it despite the fact its a pretty well known issue... so heres the post :/
the example of this i just had was in the imprisoned quest, i completed the invisible maze and the quest updated to the fighting the primal groudon. however it didnt drag me into the battle correctly and then the groudon and my first poke were just stood there (i coulda tossed my poke at the groudon to fight it and it woulda been fine but i semi didnt notice/was tabbed out) so the groudon suffocated in the wall so i couldnt fight it, as a result of this it bugged cos it thought i was in a fight when i wasnt i assume and the quest disappeared from my active quests...

so ya... this has happened a couple different times in other quests before but doesnt seem like a massive issue and its easily worked around... but heres the post i guess

**Comment by Vohras2** [comment]
Going to assume this is fixed with all the quest updates. Report if it's not.
