### ISSUE TITLE
{Quests} Choosing Wisely Vulpe Path.

### ISSUE THREAD

**Issue by PrimalCyndaquil** [ObliqueNET/Terra#254]
This bug was found by Garrator7, who did not have a Github account. 
"
1. Head into the base - the block that triggers the next stage is off to the side of the stairs, not technically a bug but missleading
2. Talk to Kaspar - the hint says to talk to Kaspar whos beside the  Ninetails statue and theres a sign that says "Kaspar" in front of him, this is the wrong Kaspar.  The quest only continues when you talk to Kaspar The Sun Prince who is further back in the base
Also Kaspar the Sun Prince's skin looks bugged, I have no idea if this is a bug or not"

**Comment by BlitzAsogi** [comment]
I just had a run through of the vulpe route. moved the trigger zone to near the door and yes the skin is still fucked.
