### ISSUE TITLE
Quests being buggy.....

### ISSUE THREAD

**Issue by R1s1ka** [ObliqueNET/Terra#259]
Hi! I was having some issues with the quests that I had.

 The first one is Avalanche. First, there was no dialogue, but with the quest hints I was able to fight 10 Abomasnow and it told me to talk to one of the people of the base of the mountain. Still no dialogue, but it gave me an 'ice pick' and that was hit. I have hit every single piece of ice of that mountain (including the space that I believe the people are trapped in) but I can't get past that part of the quest....

The second one is Remember to Exorcise..... This quest, I have gotten to where you fight the person after you find him. Then after I fight him, The thing comes out, but I can't fight it, I'm locked into the screen. I suffocated in a wall once, I dunno. It took my last quest spot, which is my I'm mostly upset by this one...

Any help would be appreciated! :)

![2019-05-03_17 07 01](https://user-images.githubusercontent.com/49657549/57176138-c7fd1300-6e19-11e9-8cb2-bfcdb1c61ee1.png)
![2019-05-03_17 17 07](https://user-images.githubusercontent.com/49657549/57176139-c7fd1300-6e19-11e9-901b-0e583e8fe246.png)
![2019-05-04_02 54 59](https://user-images.githubusercontent.com/49657549/57176140-c7fd1300-6e19-11e9-84f5-8c351192737a.png)

**Comment by starwarschamp4** [comment]
Pretty sure there is dialogue in Avalanche, seeing as how I coded it. Other issues will be looked into.

**Comment by R1s1ka** [comment]
Hi again! Noqxious helped me to get past both of my quests. Many thanks!
