### ISSUE TITLE
Quest: Pickaxe for Miner

### ISSUE THREAD

**Issue by tyltalis** [ObliqueNET/Terra#26]
Does not reward completions when trying to get amethyst from Sableye in the Sableye colony. Quest impossible to complete. Have tried dropping and picking up the Amethyst, take-all button and log-out/log-in.

Both Daithus and StabWaifu having this issue as of now.

**Comment by Soshisen** [comment]
Not impossible, for some reason the ice messes with the completion. Toss it on the ground outside should work fine
