### ISSUE TITLE
Shattered Dreams Quest, broken

### ISSUE THREAD

**Issue by IcedYoda** [ObliqueNET/Terra#260]
During the shattered dreams quest in highrift, you have to investigate a cave near the gym. I get close enough to the cave to trigger the next step to enter the cave. It then instantly tells me I run away (normally what happens when u lose to a boss), immediately following this I am forced into a fight with the boss Mega-Garchomp.....

**Comment by BlitzAsogi** [comment]
its been a good 2 months since this was listed, and going through the quest again it seems to have been fixed
