### ISSUE TITLE
Life and Destruction Small Quest

### ISSUE THREAD

**Issue by GracieTheLatias** [ObliqueNET/Terra#261]
So i went to the grass patches for LaD to replace a clock with pix grass, despite not having LaD in my quest book it triggered a fight with a cottonee and there was a quest in my book called "LaD small quest" or something like that
Kovo was there, and despite not fighting the cottonee the quest updated for him, as if the quest got confused and thought i was Kovo?

**Comment by MattBlower** [comment]
Fix is sitting in #lore waiting to be uploaded

**Comment by GracieTheLatias** [comment]
Since Matt has the fix ready, i'll just close this
