### ISSUE TITLE
Landlord expiring too early

### ISSUE THREAD

**Issue by GracieTheLatias** [ObliqueNET/Terra#262]
So recently I found out claims could expire. One player had their claim unclaim after one week and another player claimed over their house, PLUS Roonie's claim was deleted exactly two weeks after he was banned. Personally i think 60 days maximum should be the expiry date.

**Comment by Vohras2** [comment]
Going to close this for now, because I believe the update after the "Unclaiming" probably fix it. Please reopen if you here of any more things like this happening.
