### ISSUE TITLE
why am i banned from stratos it said ive been greifing 

### ISSUE THREAD

**Issue by geochaos717** [ObliqueNET/Terra#266]
i wanna appeal my ban because i feel that im not toxic and that this is a miss understanding ive just been building my structures and building a pokemon team if we can talk further that would be greatly appreciated

**Comment by MattBlower** [comment]
err this is the Terra Tracker, you want the Stratos one for Stratos bans

**Comment by Rasgnarok** [comment]
Please report it here: https://github.com/ObliqueNET/Stratos/issues.
