### ISSUE TITLE
Wild Pokemon having ownership with my name

### ISSUE THREAD

**Issue by Hawnty** [ObliqueNET/Terra#27]
Proof: 
![2018-01-06_16 15 28](https://user-images.githubusercontent.com/35160163/34636900-1427b24a-f2ff-11e7-88ab-7501bce2d1fa.png)
![2018-01-06_16 16 35](https://user-images.githubusercontent.com/35160163/34636906-1e564812-f2ff-11e7-87d5-8dc439380381.png)
All wild pokemon I encounter are owned by me. Because of this I cannot battle them to try to kill or capture them.

**Comment by Kitsune30** [comment]
#37

**Comment by Rasgnarok** [comment]
Cannot reproduce, open a new ticket if there is any news on this bug.
