### ISSUE TITLE
Ban appeal

### ISSUE THREAD

**Issue by jasehjoestar** [ObliqueNET/Terra#273]
5/14/2019

HI!
My IGN is jaseh_joestar, and as of typing this, I have just been banned for "mass stealing of items"
Situation: I was exploring the world in /rtp and stumbled across someone's unclaimed loot. There were signs saying telling people not the claim the land around it, because the guy wanted to build something there. I proceeded to steal his unclaimed items. (this happened on may 7th) I took as i pleased and thought nothing of it, since minecraft had taught me well. 

Today on 5/14/2019 I had been contacted in-game by @CenizaRey on discord (not sure of his IGN) and he proceeded to ask me questions related to the incident. I immediately was honest with him and told him, yes, I did steal from someone's chest(s) a week prior, and told him I would be happy to return any items I stole (at this point it happened a week ago, and i didn't remember all the items). I remembered taking 3 stacks of sugar cane because i had planned to build a farm, but never did anything with it. I then gave him the 3 stacks of sugar cane, and he told me I was dismissed. around 2 hours passed, and he came back to me and asked me again what I stole. @CenizaRey said something along the lines of: "it is weird that someone would report someone for stealing mere sugar cane, right?" I told him I stole more than that, and I didn't remember exactly what I stole. He proceeded to say that: "Man you must think Im really dumb..." and then I got banned. 

I understand my wrongdoings, and told @CenizaRey that I was willing to give all the items back I stole if he had told me what I stole, or pay back whatever I didn't have or already sold. I was honest with @CenizaRey and will glady give back what i stole. 

Thanks!
@DanManCanSlam#5942 on discord

**Comment by ElementalMP** [comment]
Hi! I've had a read, and there is a few things here I don't understand. First of all, you told Ceniza that you only remembered taking the sugar, but you did not mention that you took anything else? To me, that seems like something you would mention, but despite that, you didn't hand over anything that was not specifically stated? Also, here you say that you told Cen you stole more than the items you gave him, but I don't seem to have any record of that occurring? If you have chat logs of this, that would be great. Lastly, you forgot that you took several chests worth of items, despite having the items in your possession? It would be quite easy to have a quick look, and you definitely could have mentioned that at the time.

**Comment by jasehjoestar** [comment]
(5/15/2019)
"First of all, you told Ceniza that you only remembered taking the sugar, but you did not mention that you took anything else? To me, that seems like something you would mention, but despite that, you didn't hand over anything that was not specifically stated?"

After giving him the sugar cane, he came back to me 2 hours later asking for more, I then told him in-game that there was no beating around the bush, and if he had a list of the items I took, then I'd return them. Like I said, I don't remember what I stole, I've had AP Exams in the past week and am taking my AP english exam today (5/15/2019), so like I said I don't remember what I stole, I just know I stole from 3 separate chests from the same guy, the only significant Items I remember now, are around 3 stacks of ender pearls (which I sold) and the 3 stacks of sugar cane (which I gave to @CenizaRey).

"Also, here you say that you told Cen you stole more than the items you gave him, but I don't seem to have any record of that occurring?" 

Again, I told him "I don't remember what I stole" but told him if he had a list, since he came back twice, I'd give the items back.

"Lastly, you forgot that you took several chests worth of items, despite having the items in your possession? It would be quite easy to have a quick look, and you definitely could have mentioned that at the time."

Several chests is an exaggeration, It was 3 chests from the same guy. If I had the items in my possession, and I knew what they were, I stated I would've given them back, no problem. However, the fact of the matter is I DON'T REMEMBER what I stole. If you get me in contact with the guy I stole from, I could easily give back what I owe or pay off what I no longer have.

**Comment by ElementalMP** [comment]
Thanks for being so patient, I have been busy these past few days. In this scenario, I am willing to give you the benefit of the doubt, and write it off as a bit of a miscommunication. Had these circumstances you outline here been communicated at the time, none of this would have happened. I think we can both agree there. You seem to genuinely believe that you can do better, and I'm willing to go along with that. As such, I will undo this ban on the grounds that you contact a moderator and make sure that all the items get returned. I believe that second chances are an important part of learning, and that it is something we have a rare opportunity to do here. Please do not take this lightly, it is not something we give out often.
