### ISSUE TITLE
Merciless quest - No info for start or anything on wiki (+unstartable?)

### ISSUE THREAD

**Issue by Noqxious** [ObliqueNET/Terra#274]
quest became available when war effort and the other bastion quests were fixed yesterday, however there is no info on the wiki anywhere about where to start, and i tried talking to every npc in the bastion to no avail 
the quest still shows up in the quest book and i assume i have all the requirements because it doesn't say otherwise https://gyazo.com/3e079adac26781a023616c2cd4b92371
any info on where to start or if its broken would be appreciated

**Comment by Noqxious** [comment]
the4bestrole tpd me to what used to be the start point, but it pickup so i assume its broken :P 
(the start was blacksmith andy)

**Comment by Th354ndman** [comment]
This quest is currently in quarantine due to issues that cannot be currently fixed. However, I can assure you that when those issues are fixed, the quest will be fully operational.
