### ISSUE TITLE
Life and Destruction Issues

### ISSUE THREAD

**Issue by BlitzAsogi** [ObliqueNET/Terra#277]
Stage 1: Typo "After heling out celebi" when it should be "Helping"
![image](https://user-images.githubusercontent.com/24644181/57978570-f5190a80-7a42-11e9-87f8-4db5c075f9d5.png)

Stage 7: The text is white instead of the usual cyan
![image](https://user-images.githubusercontent.com/24644181/57978573-0eba5200-7a43-11e9-8d91-418829f03bc6.png)

Stage 32: Got a piece of paper with the cords to xerneas lake, which is the wrong place to go
![image](https://user-images.githubusercontent.com/24644181/57978579-22fe4f00-7a43-11e9-9221-dc29e6f2f58b.png)

**Comment by MattBlower** [comment]
Fixed so can be closed
