### ISSUE TITLE
Cherrim sprite is broken 

### ISSUE THREAD

**Issue by ShapooK** [ObliqueNET/Terra#28]
When its going to be evolved from a cherubi the sprite becomes BROKEN™ 
![cb899e8cddc2fc792ae5c2aacb9e0dbb](https://user-images.githubusercontent.com/35164973/34638616-c3545bda-f294-11e7-8ac0-3e57f357027c.png)
![195f615278e63892737b96efb895df3c](https://user-images.githubusercontent.com/35164973/34638618-c50c1ecc-f294-11e7-872b-250e28eb241b.png)

**Comment by tyltalis** [comment]
Is this only the overcast form? Because I have the sunshine form one in my box and that sprite works.

**Comment by Rasgnarok** [comment]
Fixed
