### ISSUE TITLE
Outpost Bug

### ISSUE THREAD

**Issue by Blastblaze1** [ObliqueNET/Terra#286]
Hello!

I have noticed that when I create an outpost with /outpost create <name>, often it won't let me claim more than one chunk next to it, without giving the message "This would connect an outpost and a regular claim!", even when there are no other claims at all around.

I found that it claims successfully when claims are made in a straight line, and that when the outpost is deleted, any chunks claimed through /claim remain, with only the original outpost chunk being removed. 

Through this, I'd guess that the original outpost chunk is correctly made (as an outpost claim), but any other chunks claimed through /claim are treated as ordinary claims. This explains the message, as going in a straight line would only be touching either the outpost claim or the new claims, but going off to the side would connect them.

Right now, the only way to have a large claim outside of your main claim is to create an outpost, claim 1 chunk next to it, delete the outpost, and continue claiming chunks off of the new chunk, creating a regular claim.

I don't know if outposts are finite, but this does allow infinite ordinary claims, and it's the only way to do it right now. I also don't know if this is a single isolated bug on my side or a server-wide problem, but I've seen other people with this same problem get unsolved on the discord. Either way, thank you for reading this!

Sincerely,
Blastblaze1

**Comment by Vohras2** [comment]
Should be fixed with next restart. Let us know if this persists.

**Comment by Hiroku** [comment]
I've fixed this, sorry for the huge delay. Next restart will have this take effect
