### ISSUE TITLE
Goomy has a 'bad egg' sprite

### ISSUE THREAD

**Issue by Kayouri** [ObliqueNET/Terra#29]
The egg sprites when you're looking in the PC are not in the same position. 
https://gyazo.com/da1686c2799531d11ad1b48346bc41df
The ones out of place are Goomy eggs. Only shown in the PC hotbar, not on the side.

**Comment by MattBlower** [comment]
Is the same with all of gen 6 mons and is being looked into

**Comment by Kitsune30** [comment]
#77

**Comment by MattBlower** [comment]
fixed in 7.0 so can be closed
