### ISSUE TITLE
Lost virtual vouchers

### ISSUE THREAD

**Issue by Blokus12** [ObliqueNET/Terra#294]
I had vouchers before the server was restarted (around 6pm AU time) I went to check my virtual vouchers and they were all gone. I can't remember _exactly_ what I had, but from memory it was 

These are exact:
- 1 shiny voucher
- 1 gender voucher
- 1 NPC voucher
- 1 egg move voucher

These im not 100% sure:
- 7 Ball vouchers
- 9 Size vouchers
- 9 particle vouchers

I also had 1 non-virtual shiny voucher which I redeemed after i noticed I had no vouchers. It was to test to see if it updated the vouchers screen, which it didn't but it does show 1 shiny voucher. 

Also before I lost any of them, I was unable to use them except for the NPC voucher.

IGN: Peekay1

Edit (28/05/2019): Server restarted to "fix" losing vouchers, and because of that I lost more vouchers. There was 5IV vouchers, 1 Nature voucher and 2 Egg move vouchers.

**Comment by Vohras2** [comment]
Refunded.
