### ISSUE TITLE
Purchased Claim chunks gone + Claim deleted after 2 weeks

### ISSUE THREAD

**Issue by AbyssalWanderer** [ObliqueNET/Terra#296]
took a short break of about 2-3 weeks and when i came back my claim was deleted and all of my purchased claim chunks were gone. is this supposed to happen after only 2 weeks?

**Comment by AbyssalWanderer** [comment]
Forgot but IGN:Creeperman31173

**Comment by Vohras2** [comment]
Going to assume this was dealt with. If not, feel free to reopen your ticket and we will get it sorted out ASAP.
