### ISSUE TITLE
Discord Stratos Market

### ISSUE THREAD

**Issue by gyroball12** [ObliqueNET/Terra#300]
The Stratos Market is not working with me art all. I cant add my pokemon to the market or buy pokemon from other players.  There seems to be some kind of error happening. So if you can please do something I would be grateful but take your time.

**Comment by CenizaRey** [comment]
This is the tracker for problems affecting the Terra Server. In the future for problems affecting Stratos, please use the following tracker: https://github.com/ObliqueNET/Stratos/issues/

**Comment by Vohras2** [comment]
Closing, since has been redirected to the correct place.
