### ISSUE TITLE
Missing Vouchers

### ISSUE THREAD

**Issue by Lolpopkn** [ObliqueNET/Terra#301]
I seem to have my vouchers reset to 0. I had 32 iv vouchers, 1 or 2 gender vouchers and 2-4 egg move vouchers. My IGN is TheResh.

**Comment by Lolpopkn** [comment]
Vouchers have reset again, had an additional egg move voucher that was lost. -TheResh

**Comment by BatGalByNight** [comment]
I too have lost my vouchers in the reset, my IGN is BatGalByNight, I remember what I had.

**Comment by Vohras2** [comment]
Refunded.
