### ISSUE TITLE
Issue with A Sparkling Mutation

### ISSUE THREAD

**Issue by GracieTheLatias** [ObliqueNET/Terra#302]
"i was battling it for a while before but i went to eat dinner and when i logged back on the diancie turned back into a carbink and when i right click it it doesn't do anything and when i right click on the bigger one it doesn't do anything and when i do /quests it says to fight the diancie and the hint says to right click on the smaller one but it doesn't do anything"

**Comment by BlitzAsogi** [comment]
You were probably teleported back to the original location... somehow, shouldnt have affected the quest much
