### ISSUE TITLE
Stolen Claim

### ISSUE THREAD

**Issue by LordThill** [ObliqueNET/Terra#308]
The claim belonging to myself and Skydr0p has somehow been stolen by a user by the ingame name of OtakuWill.
This user seems to have joined the server on 30/05/2019 and hasn't been back since. I have no idea how they could make a claim that surround/overwrites another claim, but me and Skydr0p are now unable to access our chests, blocks, and pokemon breeders.

Please can you undo the claim overwriting they did or just delete it so i can reclaim it.

**Comment by ElementalMP** [comment]
Sorry, I've been busy lately and this somehow managed to fly under the radar. Is it still an issue?

**Comment by Rasgnarok** [comment]
Please open it again, OP, if you are still here.

**Comment by Vohras2** [comment]
Ras said open it again, so closing since she prob forgot.
