### ISSUE TITLE
Herb Seller in Arvander? - Competitive Quality of life change label:oblique

### ISSUE THREAD

**Issue by DoobleOhh** [ObliqueNET/Terra#314]
Would it be too much to ask to have an herb seller in Arvander? Like an npc that sells "Mental Herbs", "White Herbs", and "Power Herbs"?? They get consumed in battles when they are not pvp. I only suggest it because they are used in competitive a lot and I'm guessing certain gym leaders use them on their own gym pokes. I don't see why players that do have the knowledge to use these items wouldn't have to option for these strategies.
- Again just a suggestion that would be more of a quality of life change for people who like competitive battling.

This is what I sent to Ras told me to come here and Voh will decide.

**Comment by Vohras2** [comment]
Don't really see a need for this. They are the same as focus sashes and etc, which don't have a shop either. You can still very much use them in gym battles and tournaments, as they shouldn't be used up there, so the only thing you aren't able to use them in are NPC/wild pokemon battles.
