### ISSUE TITLE
Pre-Reset Vouchers

### ISSUE THREAD

**Issue by MattBlower** [ObliqueNET/Terra#316]
Still need my 2 Shiny Vouchers and 2 Restart a Quest Vouchers from before the Reset, if I could get them back at some point I would be appreciative

**Comment by Vohras2** [comment]
Added the 2 Shiny. Not sure how to do the reset quest ones, since those are kind of external to the system.

**Comment by Vohras2** [comment]
Contact Owski for your restart quest vouchers.
