### ISSUE TITLE
Chunk Rollback

### ISSUE THREAD

**Issue by PrimalCyndaquil** [ObliqueNET/Terra#317]
What is up fellow gamers

An unclaimed chunk of my build was seemingly rollbacked. Doesn't look like griefing as a new tree appeared there n stuff. The rest of the build was claimed that area wasn't as I couldn't claim it. Dunno what's wrong with it. 
![2019-06-13_16 14 38](https://user-images.githubusercontent.com/48627086/59445047-d49c6000-8df6-11e9-8533-a92ec124f353.png)

**Comment by Archenemis** [comment]
Unclaimed chunks that go for a time without being edited will regen. You probably already had someone answer this for you by now in-game. But yeah... should always try to claim all of your builds. Even a little out of the claim is at risk for regenning.

**Comment by Vohras2** [comment]
Going to close this since it seems like this was natural chunk rollback.
