### ISSUE TITLE
My claims became unclaimed and my items are gone

### ISSUE THREAD

**Issue by bananamanbanana** [ObliqueNET/Terra#319]
I came on the server and all of my items are missing from my chests like my masterballs, z crystals, red and blue orbs, etc.

I think they might have been stolen, can you please help get them back

**Comment by Rasgnarok** [comment]
Can you please give me your username, or the coordinates of your base?

**Comment by bananamanbanana** [comment]
One of the helpers already helped me on the server. thank you though
