### ISSUE TITLE
hi i was banned for these bells things that i was duping 

### ISSUE THREAD

**Issue by 7VII** [ObliqueNET/Terra#322]
idk what to say but I was trying to ask what these bell things were and my friend just told me to dup them and give all the bells to her. next thing you know I was banned. I didn't use the bells or know what they even did

**Comment by ElementalMP** [comment]
What was your IGN, please?

**Comment by 7VII** [comment]
Appannu

**Comment by ElementalMP** [comment]
I presume this is a ban for duping on Stratos. If so, you'll want to appeal at https://github.com/ObliqueNET/Stratos/issues/
