### ISSUE TITLE
lost claims, and i was robbed

### ISSUE THREAD

**Issue by GerthyGern** [ObliqueNET/Terra#323]
coords are 5398/80/4455

all my portable crates were robbed with all of my stuff.

**Comment by Rasgnarok** [comment]
This will be looked to as soon as Looking Glass is back up to rollback. Keep ya posted in a few hours!

**Comment by GerthyGern** [comment]
any news

**Comment by BlitzAsogi** [comment]
all the shulker boxes that were caught in the logs were refunded
