### ISSUE TITLE
Lost my Claim, and was Robbed Blind

### ISSUE THREAD

**Issue by Inkythulhu** [ObliqueNET/Terra#324]
Hi, this is UN Inkythulhu on the Terra server, and I share my claim with bearhuunter and Hidu007 (just so that everyone knows they weren't the ones at fault).

I logged in just before 8pm est to reclaim our houses, only to find we've been robbed of just about everything of value we had. Ras has told me to make an issue ticket with my coords so that a rollback can be done on our claim.

Coords should be around:

x 4065
z 5319
y 192

I used to have quite a large claim, about 60-70 ish chunks worth. Enough so my house, bearhuunter's house, Hidu007's house, and our apricorn farms, while still having plenty of room to build more.

**Comment by Inkythulhu** [comment]
ManlyRhodri was nice enough to toss my claim chunks back at me, so now I'm just slowly re-claiming our area again to prevent further trouble.

**Comment by BlitzAsogi** [comment]
Your items have been refunded, DM me on discord if you have any chests i didnt see and refund
