### ISSUE TITLE
Bleach_Guzzler Ban Appeal

### ISSUE THREAD

**Issue by BleachGuzzler** [ObliqueNET/Terra#326]
Hey I am making this post to try to get unbanned. I admit to xraying and griefing/stealing items. Me and my friends have been playing on this server pretty consistently recently and have been enjoying the server. I was on the server before it wiped and returned a few months later.  I realize cheating and stealing ruins the community and I apologize.  If you guys could give me another chance it would be appreciated.  Most of the items I had on the server were legit but when I saw that the claims were reset I took the opportunity to take advantage of the glitch.  Thanks for your time. 

(Also my friend got on and saw that our house was claimed over by another player, if we could our home back that would be super appreciated as well)

**Comment by ElementalMP** [comment]
Usually we would not at all unban for this, but I am all for second chances. A big issue with giving you another shot I have is, the damage is already done. I can't really 'undo' the X-Raying, ect. I can destroy the ores and loots ect that come from mining, but I really see no concise way of going about this unban. As for the house, it has been admin claimed, and is untouchable as of this moment. If you'd like to propose some sort of agreement here, I am happy to oblige, this one time. I believe you can do better than this.

**Comment by BleachGuzzler** [comment]
Yeah I am open to any punishments you see fit. If you want to delete the ores in the chest I would be okay with that.

**Comment by ElementalMP** [comment]
Finished in DMs ^
