### ISSUE TITLE
ive been raided

### ISSUE THREAD

**Issue by TomahawkYT** [ObliqueNET/Terra#327]
ive been offline for 2days then my home gets raided cause my claims have been wiped im so angry right now thinking about quiting the game

**Comment by CenizaRey** [comment]
We're sorry this happened to you. Your claim was wiped due to a bug that affected everyone, as we mentioned in a recent announcement. We'll get your items back and punish those responsible.

**Comment by BlitzAsogi** [comment]
Item have been refunded by vohras
