### ISSUE TITLE
need some help. had my things stolen

### ISSUE THREAD

**Issue by nanthony33** [ObliqueNET/Terra#328]
i had a helper(ZhaoZilong) come help me as much as he could just now but he said i would need to get in contact with someone higher up. my chunks unclaimed over the last few days and i just got on to find out that some blocks had been broken and i had around 10 large chests of items taken. all our resources, enchanted tools and weapons, pokeballs, stones, and 100 different items all gone.  ZhaoZilong helped as much as he could but he said id have to talk with higher ups. anyone whos able to help is welcome to PM here or if im on msg/tp to me there.

**Comment by BlitzAsogi** [comment]
your items have been refunded
