### ISSUE TITLE
Ive been raided. You helped me before but i barely got anything back. The list of stuff im still missing is in the comments

### ISSUE THREAD

**Issue by GerthyGern** [ObliqueNET/Terra#329]

**Comment by GerthyGern** [comment]
hey its gerthygern from the server. Here is the list of my stolen items that i care about
around 90 rare candies
hm03 surf
hm08 Waterfall
destiny knot
everstone
5 exp shares
3 or 4 of each EV bracelet
stack of 64 ultra balls
atleast 15 of each pokeball
thats all i can really think about. idc about the rest. Those items were in shulker boxes. I marked where the boxes were with dirt in my house located at 5400 / 80 / 4453

**Comment by BlitzAsogi** [comment]
Unfortunately there is not much i can do about the shulker boxes. They were stolen before we swapped claim plugins, thus there are no logs of them being there.

The items you listed have been placed in a chest near your shulkers
