### ISSUE TITLE
Ive been raided

### ISSUE THREAD

**Issue by lMrSaltyl** [ObliqueNET/Terra#330]
I just spawned into my world into my claim and have found that all 11 of my shulker boxes were stolen along with all their contents ranging from evolution stones I cant remember how many but I know I at least had one of each to berries. Few of my chest have been looted and 11 diamonds were taken. As well as some TM's sadly i cant remember or think of all the ones that were stolen
My house location is x;4950 z;8625 y;138(8)

**Comment by Vohras2** [comment]
I refunded the shulkers that I saw, but I could only find 4. You'll need to show a mod where the others were.

**Comment by Vohras2** [comment]
Everything was dealt with, so closing.
