### ISSUE TITLE
Player-Data Clearance

### ISSUE THREAD

**Issue by SAGV0205** [ObliqueNET/Terra#331]
Sorry for the inconvenience, but may I ask to please get my player-data completely erased out from the server? I last played on Oblique's server a year or two ago, now I'd like to resume playing on the server, yet I'd like to start anew. What I ask is to get my player-data completely erased out from the server's "playerdata" folder so I can start as a new player who has never entered the server before. My IGN is SAGV0205, yet my past IGN is SGV_of_Ennor in case you don't find it. I'd really appreciate if someone could help me, thanks and sorry for the trouble...

**Comment by CenizaRey** [comment]
The Terra was already reset around 3 months ago, so this is probably already done.
