### ISSUE TITLE
2Spades Ban Appeal

### ISSUE THREAD

**Issue by 2Spades** [ObliqueNET/Terra#333]
Hey I was perm banned for Stealing and griefing today when I contacted a mod. I tried appealing my temp ban because I was sure that i was falsely accused. There werent any records of me breaking anything, But it showed that I had taken a few items (which I have no recollection of doing, especially since i didnt want to get banned in the first place). I have never once in my life been banned from a server and never have with intent broken rules. If you could, could I be unbanned. Ive just wanted to play pixelmon on the server because this was my first chance to actually be able to experience. Ive never had a computer strong enough to play the mod and I only have this computer until the 9th of july. Id really appreciate if I could join the server again.

**Comment by Rasgnarok** [comment]
We will be reviewing this, you'll get some news soon.

**Comment by 2Spades** [comment]
Alright thanks

**Comment by 2Spades** [comment]
Um this hasnt been resolved
Ive been waiting for a response

**Comment by Rasgnarok** [comment]
I apologize. You've now been unbanned, and this should have been done way sooner. Let me know if you need anything else, my discord is Rasgnarok#6969.
