### ISSUE TITLE
Trainer's Way of Life lvl 10 Pokes

### ISSUE THREAD

**Issue by Rasgnarok** [ObliqueNET/Terra#334]
right so well, Magikarp gets Tackle at lvl 15, and Professor Ras requests lvl 10 pokemon... basically forcing you to carry a deadweight poke with you until it is at lvl 10 - and it's still useless. Perhaps considering it's often the FIRST quests people do, it would be better to have a more useful pokemon up to lvl 10.

**Comment by BlitzAsogi** [comment]
Magikarps have been replaced with slowpokes

**Comment by Rasgnarok** [comment]
hot stuff, thanks blitzy
