### ISSUE TITLE
Trainer's Way of Life Battle Camera Bug

### ISSUE THREAD

**Issue by Rasgnarok** [ObliqueNET/Terra#336]
![image](https://user-images.githubusercontent.com/18584380/59970373-74ae6380-9532-11e9-8369-14f45832138c.png)
![image](https://user-images.githubusercontent.com/18584380/59970375-7b3cdb00-9532-11e9-9a43-9d41b2b2d4af.png)

Current theory is that there is not enough delay between the NPC chat GUI and the end of the battle.

**Comment by BlitzAsogi** [comment]
Delay has been added to the end of the battle for all objectives

**Comment by Rasgnarok** [comment]
Being one of the first quests people do, I feel this deserves an applause
