### ISSUE TITLE
Bright New Day's Too Early Subtitle

### ISSUE THREAD

**Issue by Rasgnarok** [ObliqueNET/Terra#338]
![image](https://user-images.githubusercontent.com/18584380/59970417-c86d7c80-9533-11e9-9e5b-70577e145845.png)
This one triggers when you enter the cave from VANHA, when it should actually be once you cross the portal into Heill.

**Comment by BlitzAsogi** [comment]
Changed it to more accurately refer to heillheim

**Comment by Rasgnarok** [comment]
man, are you coming for all the qds
