### ISSUE TITLE
Bastion's many issues

### ISSUE THREAD

**Issue by Rasgnarok** [ObliqueNET/Terra#339]
- There's legit probably 3 NPCs (that I found walking around so far)
- Has to be more lit up, or at least more reinforced
- NPCs should actually talk about the lore and the issues there, since we are in freaking hell pretty much
- Why is a dude breeding Bouffalant in a place where there's 1 patch of grass?
- No mobs (bug in landlord, really needs addressing though)

**Comment by Vohras2** [comment]
I think most of this was dealt with by our super sexy owner. Don't think you'd know them. Reopen if you find more issues.

**Comment by CenizaRey** [comment]
Kind of you to call me super sexy Voh, but you’ll find I fixed the majority of these issues.
