### ISSUE TITLE
the Quest "The Steel Curtain" stucks

### ISSUE THREAD

**Issue by PlazmaNeos** [ObliqueNET/Terra#34]
![2018-01-08_13 27 34](https://user-images.githubusercontent.com/35223886/34670824-3c67afe2-f478-11e7-8ae2-d936ed11ea9c.png)

the NPC Andy does not respond to me as he shoud

PS: The crossed-out is just a graphic bug and has nothing to do with the actual problem

**Comment by Soshisen** [comment]
1) This is not the place for your opinion.
2) Your opinion is wrong
3) You need to bring NPCs the items they want for a quest to continue

**Comment by PlazmaNeos** [comment]
and what should i bring him?

**Comment by Soshisen** [comment]
You were given an Item to bring to him. You should bring that

**Comment by PlazmaNeos** [comment]
Can you tell me what it was? I'm sorry, but I can´t remember where the quest even started.
