### ISSUE TITLE
Clues in Bright New Day

### ISSUE THREAD

**Issue by Rasgnarok** [ObliqueNET/Terra#340]
Where is the dude that is meant to clue you into the lost item's location once you are in the Bastion? Hard to tell from the lack of pop there, but it's pretty hard to find the chest if you don't know where to look.

**Comment by BlitzAsogi** [comment]
Turns out there actually wasnt someone to give you a hint in the bastion, but i added one now.

**Comment by Rasgnarok** [comment]
good to know I am not blind lmao
