### ISSUE TITLE
Clues in Just Keep Smithing

### ISSUE THREAD

**Issue by Rasgnarok** [ObliqueNET/Terra#343]
![image](https://user-images.githubusercontent.com/18584380/59971259-6e29e700-9546-11e9-8b90-897ed244ff47.png)
This is pretty much one of the most vague clues I've ever seen in a while. How are players meant to know where Silver Glen cave is to begin with anyways?

**Comment by Rasgnarok** [comment]
Actually, I can't find this spot. I am at the top of the mountain, which is near the Oxus base, and there seems to be no special ore in sight. 
![image](https://user-images.githubusercontent.com/18584380/59971335-2efc9580-9548-11e9-969c-43ff27eb34df.png)

**Comment by Rasgnarok** [comment]
I think this is actually impossible, because the current enter-zone is: 
`type=enter_zone(minx=-600;maxx=-595;miny=226;maxy=228;minz=-1116;maxz=-1113;world=Vanha)`

**Comment by BlitzAsogi** [comment]
Unsure why, but i checked the cords and they work somehow, too scared to touch while it works.
Added some crystal ore at the tip as a marker for players
Hint/Objective has been updated to reflect the location of the cave and the ore

**Comment by Rasgnarok** [comment]
You're on a roll, thanks. This might make it easier for players to locate.
