### ISSUE TITLE
Clues in Icy Delights

### ISSUE THREAD

**Issue by Rasgnarok** [ObliqueNET/Terra#344]
Okay ya so, there is no reason why the Warehouse Manager is _so_ hard to find. It should be in a labeled building, with some torch or light in front that actually makes it visible (since the door is opposite to the player's view) and DEFINITELY should not have the NPC buried deep down 3 floors. At the very least, there should be NPCs talking about how the big warehouse boss stays only at this desk on the bottom floor... or really, anything better.

**Comment by Rasgnarok** [comment]
also major s/o to Elk for showing me where the NPC was

**Comment by BlitzAsogi** [comment]
Added more dialogue to the Ice Cream seller to direct the players into the house
Added dialogue option to the NPC inside the house and direct them down the stairs
