### ISSUE TITLE
Battle Loop in Just Keep Smithing

### ISSUE THREAD

**Issue by Rasgnarok** [ObliqueNET/Terra#345]
I _think_ the delay is too small, cause I was put in battle with Salamence as I just teleported in front of the PC... I am nowhere near the top of the mountain. 
![image](https://user-images.githubusercontent.com/18584380/59971643-c6b0b280-954d-11e9-9526-183916482e1f.png)

**Comment by BlitzAsogi** [comment]
Delay has been removed

**Comment by Rasgnarok** [comment]
oh goodies
