### ISSUE TITLE
Banned for something i didn't do

### ISSUE THREAD

**Issue by SypherIsHere** [ObliqueNET/Terra#346]
Yesterday i was online for one hour and i helped a friend to build his house and i was breeding my pokémon.
In short, I was banned for something I didn't do, the last time I was banned was for claiming the chunk of a my friend.
From then on I made a promise with myself "I will not grief never again"
I was perm banned for Griefing on terra but i didn't do that!
I simply took a shulker box that was placed in a plain, I didn't steal or grief.
I hope I can get back to playing because of my great interest in this server
And I will never do anything like that again (steal even if it belongs to no one)
IGN=SypherIsHere

**Comment by CenizaRey** [comment]
You don’t know if the shulker box belonged to nobody. You say you didn’t grief or steal, but you did. In the rules it states do not take anything that isn’t yours, even if it isn’t claimed. “I simply took a shulker box  that was placed in a plain, I didn’t steal or grief”. If you want to be unbanned, I would suggest familiarising yourself with the rules of our server.

**Comment by SypherIsHere** [comment]
> You don’t know if the shulker box belonged to nobody. You say you didn’t grief or steal, but you did. In the rules it states do not take anything that isn’t yours, even if it isn’t claimed. “I simply took a shulker box  that was placed in a plain, I didn’t steal or grief”. If you want to be unbanned, I would suggest familiarising yourself with the rules of our server.

In the shulker box was wrote "This is a present for the first person that found this shulker"

**Comment by CenizaRey** [comment]
Regardless, you stole from the house of another player about two days ago. Since you had done so before, and had already served a 3 day tempban, you were banned permanently. This ban is here to stay. You will not be unbanned.
