### ISSUE TITLE
Avenging Flames quest bugs

### ISSUE THREAD

**Issue by Thunderman1000** [ObliqueNET/Terra#347]
The avenging flames quest has two bugs towards the end of the quest. The first one is when you go to fight the grunts and when you go to fight the end boss it doesn't teleport you and when you leave you have to restart the grunt beating. The second bug is when you beat the final boss and it sticks you in the battle screen and when you relog it resets back to the grunts again.

**Comment by BlitzAsogi** [comment]
Quest has been fixed by ElementalMP
