### ISSUE TITLE
i was banned for xraying chests in dungeons

### ISSUE THREAD

**Issue by TomahawkYT** [ObliqueNET/Terra#349]
i was just looking for chests in dungeons andi got banned and yes i used wurst i wont do it again if a get a atleast a week ban or a temp ban i just wanna play again

**Comment by ElementalMP** [comment]
Using a hacked client is clearly stated as being against the rules, as well as using xray mods. After the ban you proceeded to go argue with players in support, stating that it should be equal consequences compared to raiding. There is a fine line between raiding a player, which can happen as a result of for example, not realizing that a structure is player built. On the other hand, installing forgewurst to your client really isn't something you can do by accident, so I am confused as to what made you think it would be okay to use?

**Comment by TomahawkYT** [comment]
never said it was ok to use but if hacking is against the rules equaling a perm ban than what about all the other things

**Comment by ElementalMP** [comment]
Bans are circumstantial and vary from case to case. There is no open-shut consequence for breaking a rule. The difference between say, spamming chat or using a clientside modification to cheat at the game is pretty clear, and will thus be treated differently. I can't really understand where your point is here, you seem to be arguing that I should ban everyone that breaks a rule? In addition, if you knew it wasn't okay to use, what made you think it was a good idea to install it in the first place? Did you think you would not get caught?

**Comment by TomahawkYT** [comment]
can you guys atleast split all my loot with closetbrony and FBI_Agent_Timmy

**Comment by TomahawkYT** [comment]
or just wipe my account but just please dont get rid of my shiny ditto ill do anything to get unbanned all the others servers are not the same ill do anything

**Comment by ElementalMP** [comment]
> 
> 
> can you guys atleast split all my loot with closetbrony and FBI_Agent_Timmy

I obviously cannot agree to this, as unfortunate as it is. You were xraying to dungeons, so I have no way of knowing what is legitimate and what is not. I really don't think there is much else to discuss here, so I'll close the issue.

**Comment by TomahawkYT** [comment]
its not only the stuff in my inventory was xrayed thats it
