### ISSUE TITLE
Incorrect wiki prices

### ISSUE THREAD

**Issue by ServantGirl** [ObliqueNET/Terra#35]
**Working list**
Enchantment Table is _150, should be 75_
Every Ball  Buy is 75, 150, 200. Should be 38, 75, 150 for poke, great and Ultra. Sell prices are also incorrect. Nest, Lure, love ect are Buy 100, should be 50. ((Basically every ball was nerfed in buy and sell prices)) 
Diamond _50, should be 15_
Emerald is _50, should be 15_
Gems(held item) _50, should be 15_
Mail is _no longer sellable_

Further more I feel that the wiki should tell you which towns have certain shops, but you can call that pie in the sky.

**Comment by Kitsune30** [comment]
Mail is intended to be sellable, there a few that are not in the config. Can you specify which aren't sellable?
I have updated the rest of these

**Comment by ServantGirl** [comment]
heart, Inquiry, and fab.

Inquiry, it should be noted drops from Wabba near every kill.

**Comment by Rasgnarok** [comment]
@Kayouri , Economy page should probably include the locations of all these shopkeepers.
