### ISSUE TITLE
The Steel Curtain - NPC not registering item

### ISSUE THREAD

**Issue by Nattryon** [ObliqueNET/Terra#350]
I’ve found Andy the Blacksmith in the Bastion, but when I speak to him with the required item (Iron Supplies)  in my inventory he just gives his usual dialogue. I’ve even held the item in my hand while clicking on him. I don’t know if the quest or the item is bugged.

**Comment by BlitzAsogi** [comment]
The NPC UUID was recently noticed to be misplaced and has been reuploaded, should be working fine now.
