### ISSUE TITLE
The Jewel Thief - Checkpoint not triggering

### ISSUE THREAD

**Issue by Nattryon** [ObliqueNET/Terra#351]
I’m at the stage where you’re supposed to leave Agni through the cave and encounter the sableye, but even when I take off my running shoes I’m not triggering the battle. I’ve left Agni before starting the quest, so that may have bugged it out for me.

**Comment by BlitzAsogi** [comment]
the battle isnt at the exit of agni, you're supposed to find the cave at the exit of agni.
