### ISSUE TITLE
The Electric Mouse & The Arbiter's Downfall Conflict

### ISSUE THREAD

**Issue by ErwinJose** [ObliqueNET/Terra#352]
If these two missions are active I believe the Guardian Raichu from Arbiter's Downfall counts towards the Electric Mouse's Raichu count instead of advancing Arbiter's Downfall

**Comment by ErwinJose** [comment]
I think this may have also messed up Electric Mouse as I can't talk to the worker after finishing the 10 Pikachu/5 Raichu

**Comment by ErwinJose** [comment]
Well it seems to have resolved itself after I got ejected from the secret hideout in Stardust Poachers

**Comment by BlitzAsogi** [comment]
The way our quest system works is that any pokemon of the name you kill will help progress your quests, even if they are from another quest.

For the Electric Mouse, the pikachu was supposed to ambush you as you entered the building.
