### ISSUE TITLE
Quest Bugs

### ISSUE THREAD

**Issue by TheShadyTiger** [ObliqueNET/Terra#353]
Hi,

I've been trying to complete some quests with some friends, but they are at times excruciating. They are necessary to progress in the game and to get legendaries since they don't spawn in the wild, but they don't work. It's clear that a lot of effort has been put into making these quests, which makes it all the more infuriating that they don't work. For example, I'm trying to complete the quest "Pick your Potion" along with some friends. We figured out the riddles which was very fun, and then when we go to the location that the riddle requires, the quest updates for some of us and not all of us even though we did the exact same thing! This is not an isolated problem, either. Is there something we are doing wrong? Is there something we are supposed to do in order to update quests?

-Thanks

**Comment by BlitzAsogi** [comment]
Quests are a bit finnicky, but thats how minecraft is at times. Im assuming that most of the issues you are getting are from enter zones, which you can actually overshoot if you're going too fast for the game to register. Common ways to fix this are to slow down and avoid running with thunderstone armor/running boots.
