### ISSUE TITLE
ahmadaradii Ban appeal

### ISSUE THREAD

**Issue by AhmadAradii** [ObliqueNET/Terra#355]
Hi there!

  My name is Ahmad and I was trying to login today to the server and for some reason I got banned with a long message saying that I did grief and steal or some sort of thing and I have like **3 days** to wait till the banned gets removed and actually I wasn't even online yesterday for some personal reasons in my life. So I am freaked out that I saw the ban and the message is too long and I have a picture of the message which I will upload it here. Basically I wanna know why does it say griefing when I wasn't around and been banned like this and if it was just accusing me please just remove it so I can play since I don't have anything to do in my life just playing in the server after seeing many servers and I see this is the best especially for f2p players like me.

Link: https://prnt.sc/o8xrdn

Thanks in advance for understanding the situation that I am in and sorry for the trouble so I hope we can get in touch soon.

Best regards,
AhmadAradii

**Comment by CenizaRey** [comment]
After the landlord claim incident, we put out an announcement that said we’d be on special alert for griefers for the next few weeks. This was made very clear. Unfortunately, a grief was reported and you were found to be the culprit. It doesn’t matter if you weren’t online yesterday. It doesn’t matter if you did the grief 24 hours or a week ago. The fact is, you _di d do it_. As a result, we were left with no choice but to ban you for the standard 3 days, which you will have to serve. We appreciate the apology, and you will be unbanned automatically when these 3 days are up.

**Comment by AhmadAradii** [comment]
> After the landlord claim incident, we put out an announcement that said we’d be on special alert for griefers for the next few weeks. This was made very clear. Unfortunately, a grief was reported and you were found to be the culprit. It doesn’t matter if you weren’t online yesterday. It doesn’t matter if you did the grief 24 hours or a week ago. The fact is, you _did do it_. As a result, we were left with no choice but to ban you for the standard 3 days, which you will have to serve. We appreciate the apology, and you will be unbanned automatically when these 3 days are up.

So... you are saying that someone saw my name and reported me or what ? cuz i don't really understand that part but the part about the announcement i understand it very clearly.

**Comment by CenizaRey** [comment]
We have a method of seeing who broke what block and when, and your name came up in a griefed area.

**Comment by AhmadAradii** [comment]
> We have a method of seeing who broke what block and when, and your name came up in a griefed area.

Oh god, not this again. I guess I have to talk to my little brother and make him understand what grief means again. Sorry for the trouble again and wasting your time like this so I will just change my mc account so this shouldn't happen again. Just for my curiosity what is the name of the landlord that I was banned cuz of it? I just want to do something as an apology to him/her about what happened and had them to go through all of this.

Now I have to wait these 3 days to play again.
