### ISSUE TITLE
ban appeal geochaos717

### ISSUE THREAD

**Issue by geochaos717** [ObliqueNET/Terra#356]
i have been accused of griefing. the only "griefing" remember happening  is when me and a friend had a falling out and we had an argument over some items but that was both of our items but im a solo player and want access to the server and my old stuff is there any way to make this possible?

**Comment by ElementalMP** [comment]
You say here you only griefed one time, but you had 2 separate warnings for griefing before being banned after a third time. Additionally, this all happened pre-reset so unfortunately there is not going to be much of your old stuff left. For this reason, I really cannot trust you not to do it again, given the amount of warnings you ignored.
