### ISSUE TITLE
"Choosing Wisely"

### ISSUE THREAD

**Issue by DerpyDevils** [ObliqueNET/Terra#358]
so im trying to do the "choosing wisely" quest and im at the place where you are suppose to pick the guild you want to go in. I  wanted to pick "Oxus" however its not working and when i check my quest book it tells me to "go up the stairs". i asked in chat and was told thats the step after you pick the guild however i havent really picked any guild yet.

my IGN is xXDerpyDevilsXx

**Comment by BlitzAsogi** [comment]
Im unsure of what the issue is, when you next get online, you can tell the QD to reset the quest, and link them this issue if they are unsure.
