### ISSUE TITLE
Steel Curtain quest item

### ISSUE THREAD

**Issue by Nattryon** [ObliqueNET/Terra#359]
Andy the Blacksmith is still not accepting the Iron Supplies, I think the item might be bugged (has been taken out of inventory and put into chest then taken back out, don’t know if that would mess anything up)

**Comment by BlitzAsogi** [comment]
Turns out, Andy was being a lil bitch again! I've taken the liberty to remove his need from the quest, all you have to do now is talk to Alexander again in the Silver Glenn cave, by the mawiles
