### ISSUE TITLE
Ban Appeal 

### ISSUE THREAD

**Issue by toughfastman** [ObliqueNET/Terra#360]
Name:ToughFastMan
Reason for Ban Bad Language

I was away from my computer and my boyfriend decided to "prank" me and get me banned on the server. I apologize on his behalf.

**Comment by BlitzAsogi** [comment]
Our head mod will have a look at this when he has the time, but do note that we do not care about who was in possession of the account at the time, your account is your responsibility.

**Comment by toughfastman** [comment]
It will not happen again, I can guarantee it

**Comment by ElementalMP** [comment]
I can see this being a legitimate story, so I will give you benefit of a doubt. I've unbanned your account, but please do take care of it. I can't be so lenient if this should happen again!

**Comment by toughfastman** [comment]
i can assure you it will never happen again
