### ISSUE TITLE
Sellinq's Ban Appeal

### ISSUE THREAD

**Issue by Sellinq** [ObliqueNET/Terra#362]
Dear Oblique Staff Team,

Hey I tried joining today on tuesday 16 of July 2019, to find out I was banned I havent logged in for about a week now and last time I logged in I wasn't banned the reasoning said on my ban is for "Griefing" Yet I would not know how this would come around from, Thanks for your time on reading this.

Sincerely Sellinq.

**Comment by ElementalMP** [comment]
You were banned from Terra for repeated griefing against multiple users, after being warned previously for the same thing. The last person you griefed was Creeperman31173, during the claim deletion bug. Repeatedly breaking rules has always resulted in a permanent ban. You logged off before the grief was reported, and banned before you logged back in.
