### ISSUE TITLE
Inquiry: Alt Account Policies

### ISSUE THREAD

**Issue by 77wisher77** [ObliqueNET/Terra#365]
I would like to ask if Alt accounts are allowed on the Terra server. And if so what exactly can you do and can't do.

Ideally I would like to use an alt account to claim so no individual in a group has to trust anyone they don't wish to trust.
My scenario here is I stream and am inviting viewers to play with me as I stream and it would useful if I don't have to /trust them with my main account. (which would let them potentially have access to my personal base).

**Comment by ElementalMP** [comment]
Alt accounts in themselves are allowed on Terra. Maybe you want to give something to your mate anonymously, or if you lost all your friends and wanted to look like you had some. You can't use an alt to gain things that are capped per-player, like claim blocks, inviteafriend or gym rewards. You also could not use an alt for things like ban evasion, but that is just good common sense.

**Comment by Vohras2** [comment]
I'm going to assume this has been sorted and close the issue. If you have further questions, feel free to open another ticket.
