### ISSUE TITLE
Ban appeal 

### ISSUE THREAD

**Issue by Clapanese** [ObliqueNET/Terra#368]
I was running around and I didn't know what to do so I dug down to try to find a cave to get the rest of the fossils for my collection. when I dug down there was a shiny shuckle and I went to catch it. when I was trying to catch it I got banned for "pokeradar". Please unban me I did nothing wrong :'(

**Comment by ElementalMP** [comment]
You were walking through a plains biome, and proceeded to look directly at a shiny shuckle through the ground spawned many blocks below you, inside a cave. You then dug straight down directly on top of the shuckle, and made no attempt to find caves prior to the spawning. If you didn't use radar, how did you see it? Cheat modifications to the client are always a ban, so I am confused as to why you think you deserve to be unbanned.

**Comment by Clapanese** [comment]
i didnt see it im telling you it was literally a coincidence  i just started digging down to find a cave to get more fossils the plains i was running in was right outside my house

**Comment by Clapanese** [comment]
please man, im just trying to play some pixelmon, i have nothing else i want to play right now and your server is the only one that i felt was worth it. im not cheating and i never planned on it., Please

**Comment by Clapanese** [comment]
ill record my gameplay from now on so we never have this problem again please

**Comment by ElementalMP** [comment]
I'm sorry, but this really doesn't seem plausible. The chances of you finding a cave in the method you did as accurately as you did are slim enough, not to mention the chances of it being immediately after a shiny was spawned on you, directly on top of the shiny are astronomical. In addition, fossils do not spawn in caves alone, they only show up in gravel deposits? 
I cannot trust this as a reasonable story, so for this reason, I will not be unbanning the account.
