### ISSUE TITLE
ArcticWolf_11's Ban Appeal

### ISSUE THREAD

**Issue by SandyPier2** [ObliqueNET/Terra#369]
Name: ArcticWolf_11
Server: Terra
Ban Reason: X-Ray

First of all, though you're probably not going to believe it but, I literally had no idea I even had it installed... Hear me out, I asked Elemental what he thought what rule I was breaking because I literally was confused as to why he was messaging me. Kept asking trying to get to the bottom of it then he said I had X-Ray. No clue I even had it, was typing to ask if he wanted me to reinstall the pack or something, then I get banned. Also I don't know but haven't you thought that maybe someone else other than me uses the computer?... Hence why I was asking if you wanted me to reinstall the pack, thus getting rid of it. Now if in the future it's back there again then yeah I understand getting banned for that. I really do hope you understand and that second chances will be granted, thank you.

**Comment by ElementalMP** [comment]
As unlikely as this seems, I am willing to give you benefit of a doubt and believe you. As long as you uninstall the modifications, I can unban your account. Please make sure it doesn't happen again.
