### ISSUE TITLE
Annoying Bug

### ISSUE THREAD

**Issue by VoidLordMaximus** [ObliqueNET/Terra#37]
For a hour as of writing this post I have been only finding wild pokemon that say they are owned by me and as you can see in the picture are not. I do not own a breeder or the pokemon that say I own them I have relogged multiple times and it keeps happening please help me.
![2018-01-09_05 37 48](https://user-images.githubusercontent.com/35260027/34719151-75e77524-f4ee-11e7-9fc4-71eaa9bb4315.png)

**Comment by Rasgnarok** [comment]
Duplicate, closing.
