### ISSUE TITLE
I just need some help with this I'm appealing for a ban on  the website where you buy   ranks I don't know why I'm banned  Minecraft account is over 6 years old it could be anything I just need some help 

### ISSUE THREAD

**Issue by Nicholasissomad** [ObliqueNET/Terra#370]

**Comment by Vohras2** [comment]
Most likely cause is Buycraft blacklisted you for charging back on a server.

**Comment by Rasgnarok** [comment]
You need to contact Buycraft and have them explain the ban. It's called seller protection, and basically blacklists MC accounts that created heavy chargeback requests.
