### ISSUE TITLE
Claim expired and raided

### ISSUE THREAD

**Issue by Iunala** [ObliqueNET/Terra#373]
So when we first started building a base, my bf had claimed one chunk at the corner of the build because I didn't have enough money at the time to claim more. He went on a trip for a month and was unable to play for that entire time, so it expired. When it expired, I was away on my own trip. I finally came back to play again and saw that that corner was unclaimed and all the stuff in it was raided :( I think someone who recently started building a home nearby may have taken my stuff, but idk. I had a mechanical anvil setup and a few chests with apricorns are other things in them. My IGN is Iunala and his IGN is OfficalNat. Please help :( thanks

**Comment by ElementalMP** [comment]
This should have been seen a lot sooner. When you are available, let me know and we can sort it out :)

**Comment by Vohras2** [comment]
Closing this because the base would have reverted by now if it hasn't been dealt with.
