### ISSUE TITLE
Purchases made before the server wipe

### ISSUE THREAD

**Issue by Ratzilla320** [ObliqueNET/Terra#374]
I used to play on Terra last year and made quite a few purchases/donations. I just recently returned earlier this week and luckily kept my Enigma rank, but all the items obtainable through said rank as well as other purchases were gone. Below this message I will leave the item name, transaction ID's, and the date of purchase for each one. All of the transactions listed are under the username/ign Ratzilla320, and will not include purchases I've made for other players under their username.

1x PokéEdit Pack
Transaction ID: 4LK795092R0667451
Date: 6th December 2018 19:24

1x Mystic Rank
Transaction ID: 1AX09902CK143660U
Date: 6th December 2018 20:52

1x Mystic+
Transaction ID: 62A44186KL9957614
Date: 8th December 2018 2:09
 
1x Random Shiny Pokémon
Transaction ID: 137841503D137341H
Date: 9th December 2018 6:42

1x Random Shiny Pokémon
Transaction ID: 5D94439279104543G
Date: 9th December 2018 7:57
 
1x 10 Store Crate Keys
Transaction ID: 6K38179367048213S
Date: 16th December 2018 5:15

1x 10 Store Crate Keys
Transaction ID: 4GB32206FK662902X
Date: 16th December 2018 23:50

**Comment by BlitzAsogi** [comment]
This is something Ras would need to deal with, and she just left for bed. Ill ping her in discord with this.

**Comment by Vohras2** [comment]
Pretty sure these were refunded, so closing now. Reopen if that's not the case.
