### ISSUE TITLE
Pokemon lost after reset

### ISSUE THREAD

**Issue by TheShadyTiger** [ObliqueNET/Terra#375]
Hi,

I didn't think i would be very affected by the wipe since i haven;t been playing much lately, but I do still hatch my eggs from time to time. It says that entities were lost but I didnt think that included pokemon in my PC. Basically, I breed Eevee's and two of my breeders are also breeding Snorlax's. In the reset, I lost a female modest 5iv Eevee (no physical attack), and a female adamant 5iv Snorlax (no special attack). The snorlax also had about 30 special attack but thats not important couldnt care less about that. I mentioned this in the chat and i was told to make a support ticket. Is there anything that could be done about this? I dont have a screenshot or anything, but I do have over a page in the PC filled with Snorlax's and half a page of Eevee's (all fairly high IV) if that at least provides proof that I have been breeding a lot of them. My IGN is Chipy_chip by the way.

Thank you.

**Comment by Rasgnarok** [comment]
I am not sure if this was adressed in game, because I feel we have seen this on discord, but if that's not the case, please report to our support channel, or reopen this ticket.
