### ISSUE TITLE
Bammaboy's ban Appeal

### ISSUE THREAD

**Issue by oshawott6634** [ObliqueNET/Terra#377]
Hi This is Bammaboy and I am making the Ban Appeal so i can come back on and play with my friend. I was banned for Greifing and for doing stuff that I wasn't supposed too. I am Greatly sorry I am 19 and I can understand if you still hate me but I would like to have another chance playing on the server.  Thank you for reading. - Bammaboy
![My Signature](https://user-images.githubusercontent.com/32103595/62845180-ea08fb80-bc7a-11e9-9e64-4333c9215ebe.png)

**Comment by ElementalMP** [comment]
As much as it would be nice to be able to unban you in good faith, there is no way I can justify you deserving it. There is no way we can trust you after you:
-Spammed the server with alts after being banned.
-Tried to spam staff members and global chat with phone numbers.
-Attempted to guilt trip several staff members with suicide threats.
-After being removed from builder, griefed our admin claim.
-Abused a staff rank's permissions for personal gain.
Quite a list, in fact. You caused mass upset for everyone involved, and even got your mates removed alongside you. For these reasons, and for the safety of all our existing players, you will not be unbanned.

**Comment by oshawott6634** [comment]
Nah

**Comment by oshawott6634** [comment]
Dude Seriously Unban me dang is it that to hard to do it is /unban Bammaboy

**Comment by starwarschamp4** [comment]
Dude, you're not getting unbanned. Or any of your 100 alts.

**Comment by oshawott6634** [comment]
I dont have any alts

**Comment by ElementalMP** [comment]
I'm sure it would be rather easy to run that command, although unfortunately I will never know.
What I do know is that banning and hunting the masses of alts you spammed us with definitely wasn't easy, and nor was dealing with the upset players you left behind. There is absolutely no way we can trust you, and I don't think any of us really want to try and chance it. You directly went against what Blitz and I asked of you from the start, and all we wanted was to sleep knowing we didn't have suicide threats in public chat. I haven't seen a single reason to forgive you for anything, you used up your second chance the moment you decided to cause a riot over your firing. We weren't even going to ban you, you gave us no choice. Further posts on this tracker will result in a ban from it. I will not be unbanning this account.
Good day.

**Comment by BlitzAsogi** [comment]
>"Dude Seriously Unban me dang is it that to hard to do it is /unban Bammaboy"
Dude seriously dont abuse staff persn is it that hard to do it is /gm 0
