### ISSUE TITLE
cant battle 

### ISSUE THREAD

**Issue by soulerox** [ObliqueNET/Terra#379]
I Can't battle Pokémon or trainers and when I try to make a wondertrade it Writes to me  I'm in the middle of a batttle
![image](https://user-images.githubusercontent.com/54169725/63152453-8f71f580-c014-11e9-93fc-012185cb74a3.png)

**Comment by McConnell2111** [comment]
Try doing /endbattle. If not then spectate someone else’s battle and the problem should be solved
