### ISSUE TITLE
Quest rewards on full inventory are deleated

### ISSUE THREAD

**Issue by ServantGirl** [ObliqueNET/Terra#38]
If you have a full inventory and complete a quest that yields an item reward, you will get a message saying 'Inventory full, <item> dropped on the ground' However it does not drop on the ground, it is just lost.

The same happens for loot from KOed pokemon if you click 'take' on a full inventory.

**Comment by Rasgnarok** [comment]
@Kitsune30 This is due to full inventories not dropping items, could be related to GP.

**Comment by Kitsune30** [comment]
Its possible, with spawn items being disabled, I'll need to tinker a bit
