### ISSUE TITLE
Pokemons evolve in to the same pokemon

### ISSUE THREAD

**Issue by Zarzuf** [ObliqueNET/Terra#381]
My metapod upon reaching level 10 evolved in to ... metapod (intead of  butterfree)
and my hoothoot upon reaching level 20 evolved in to hoothoot (instead of noctowl).

Is there  something that can be done to make them evolve properly?

**Comment by CenizaRey** [comment]
Unfortunately this is a bug with the mod itself, and there’s very little we can do about it serverside. Just ask a helper or a moderator to evolve your pokemon, and they’d be happy to do so.

**Comment by Zarzuf** [comment]
Solved, thank you :)

**Comment by Zarzuf** [comment]
Actually it keeps happening.
Today my electrike and my shroomish evolved in themselves instead of their proper evolutions.
Does it means that I'm "cursed" with this bug from now on?
It's quite inconvenient (both for me and for the helpers) to have to ask for a forced evolution everytime.

**Comment by CloudingzOblique** [comment]
Yes, you'll just have to wait for them to update the mod. Just DM me on Pixelmon when you need me to evolve it, I'll be happy too.
