### ISSUE TITLE
Ban Appeal

### ISSUE THREAD

**Issue by Assmosis** [ObliqueNET/Terra#382]
I think I got unfairly banned. Nowhere in the server was I prompted to read any rules, nor did I see where to find any. Someone in the chat was talking about pirating a game and so I half jokingly called him a faggot for that and immediately got permabanned from the server. Now I don't think thats a fair way to get permabanned from the server and i did not know that would happen. Because like i said there were no rules that i saw whatsoever, and on top of that i saw plenty of other people using swear words, that got censored so i didnt think that would be any different, and dont know why it was any different. So id like a second chance to play the server, read the rules and whatnot. So that doesnt happen again. That was pretty harsh reaction to a word i didnt realize was so against the rules

**Comment by CenizaRey** [comment]
The rules are clearly listed in both, the /rules command which you are prompted to review from the moment you join the server. On top of that, there’s a very clear rule board mere blocks away from you when you first spawn in.

You must understand that faggot is different from other swear words in that it’s a targeted slur for a specific group of people. We agree that certain words carry more weight than others, and not all swear words are created equal. I’m not approving or declining your ban appeal, but I’m concerned by the fact your first reaction to someone talking about pirating a game was to immediately drop a slur. It’s not funny, or clever, and I think you should take a look at yourself before you claim your ban was unfair.

**Comment by Assmosis** [comment]
> The rules are clearly listed in the /rules command which you are prompted to review from the moment you join the server. On top of that, there’s a very clear rule board mere blocks away from you when you first spawn in.
> 
> You must understand that faggot is different from other swear words in that it’s a targeted slur for a specific group of people. We agree that certain words carry more weight than others, and not all swear words are created equal. I’m not approving or declining your ban appeal, but I’m concerned by the fact your first reaction to someone talking about pirating a game was to immediately drop a slur. It’s not funny, or clever, and I think you should take a look at yourself before you claim your ban was unfair.

No I understand why I got banned for it its just like, I obviously mistakenly glossed over where to see the rules and think that an instant permanent ban is a little over the top. At least some form of a warning I guess. It was meant as partly a joke and not to be genuinely awful or homophobic. That's why I say it's a bit unfair. I understand that probably wasnt a good thing to say which is why i want the opportunity to be able to play the game and yknow actually be able to read the rules. Just asking you to reconsider the ban and I'll take this as a pretty clear warning, and that something like that won't really happen again

**Comment by Vohras2** [comment]
Closing this since it's an old appeal.

**Comment by Assmosis** [comment]
Wow that really required two separate emails
