### ISSUE TITLE
Who is this 

### ISSUE THREAD

**Issue by SkullDinosaur** [ObliqueNET/Terra#389]
![2019-09-23_17 47 24](https://user-images.githubusercontent.com/55722393/65472901-771ea300-de2a-11e9-806b-7c0949691ae5.png)

**Comment by ElementalMP** [comment]
Bammaboy is the named of a banned staff member, they decided it would be a good idea to abuse permissions for personal gain and caused a lot of drama when they were called out for it.

**Comment by SkullDinosaur** [comment]
oh ok
