### ISSUE TITLE
Remember to exorcise boss loss glitch 

### ISSUE THREAD

**Issue by ServantGirl** [ObliqueNET/Terra#39]
If you loose against the boss it teleports you inside a wall and you suffocate.

**Comment by Th354ndman** [comment]
There is also another glitch that is easily replicated with this boss, it will force you into third person, but your camera wont follow you or your actions, usually happens to me at the same time as it sending me into the wall.

**Comment by Soshisen** [comment]
Mon fixed this awhile ago
