### ISSUE TITLE
Mega Ring/stupid glasses

### ISSUE THREAD

**Issue by McConnell2111** [ObliqueNET/Terra#390]
issue with mega stone disappearing. no, real way of getting them back other than keep relogging. defeating mega bosses does not give the ring back and the give mega stone command(from leads doesnt work either) admiral had this issue during the oblique cup. please fix this is affecting gym battles too :/

**Comment by Vohras2** [comment]
I -think this is fixed? Not sure, but report to Pixelmon if not.
