### ISSUE TITLE
Unbreeding Pokemon

### ISSUE THREAD

**Issue by MaliciousMe** [ObliqueNET/Terra#392]
Sometimes when doing /unbreed <slot> the message that appears asks if you want to make the pokemon breedable, when it is already a breedable pokemon. The confirmation messages says that you've made it unbreedable however.

**Comment by HyperWilson2** [comment]
Yeah i've noticed that, im guessing a checksum of some kind hasn't been implemented yet to change the dialogue.

**Comment by Vohras2** [comment]
I believe this has been fixed.
