### ISSUE TITLE
Farewell, Oblique - HyperWilson

### ISSUE THREAD

**Issue by HyperWilson** [ObliqueNET/Terra#394]
Listen ras, after quite a lot of thinking, i've decided upon a few things.
But first, i'd like to address what led up to this moment for those unaware of what really happened.
Someone by the name of "Soxiel" (who happens to have been around for quite a while on the server) recently joined back after a while of inactivity.
...and discovered that his base was utterly griefed.
He decided that the best thing to really do, was to give out some of his shiny pokes (1 for each person) to newcomers of the server as well of veterans like me who'd happily take the resources and other cool shit.
He was able to give out 1 shiny poke, before being banned for apparently "breaking the economy" like giving one 1 shiny to 5-6 who actually showed up would ruin the economy, so he was banned. He was later forgiven for this mistake and thus unbanned only to be banned once more by rasgnarok.
I thought that was rather reprehensible, for someone like him (who decided he wanted to leave for good anyway) to do some good and make a few peoples days by giving them 1 shiny and some items he managed to keep on him or in his enderchest.
I on behalf of him, contacted rasgnarok personally to relay his complaints.
I also relayed some of my own grievances.
I've discovered multiple destroyed bases in which people who would actually join back, would complain about the ruins. The moderators would often do nothing, those people would often leave and never return.
I myself had a pretty decent neighbor, who built something akin to a castle/sewer like base near my home, and they had showed me inside a while back when i first joined.
They had TONS of goodies, and a decent base to top if off.
About a week or two ago i started playing on the server again, and shortly after i resumed my progress on this server i decided to visit his base, most of it remained intact.
Except his storage area... which was completely ransacked. The one responsible left signs behind mocking the owners, the moderators, and so on.
When i had relayed the coordinates to him so he could find who was responsible, i was instead banned, confused, i texted him on discord where he ridiculed me liking me to some kind of malicious manipulator of sorts, laughing at me for crimes i know i didn't commit.
But when he revealed a screen cap showing who placed them, and the ip's associated, it was MY ip. MY account followed by a string of account names i know nothing about!
I must admit, i don't know how someone achieved this, i don't know what to say in my defense of that. But... Is there really anything to say?

So, this is my farewell to you Oblique.
At this point, i don't care about being unbanned. It's not about that anymore.
It's about clearing my name that i've established as well-intentioned as i could.
I'm sorry i couldn't do more for you all. I really tried! I helped as many people as i could while fulfilling my own desires to partake on the server.
I filled my base with tons of items gathered from as much pokeloot as i could get my hands on.
I IV bred for days on end trying to get a perfect IV version of my favorite pokemon.
If i had known i'd be banned for trying to report someone else's crimes, you ask, would i still have done it? I can't say, what are the chances my reports did anything anyways? I reported quite a few of those bases and it didn't matter much at all. Until it meant everything.
I immersed myself in the world you all built, and it burdens me that i might never see it all.
I made custom textures and sent them to rasgnarok so he could add them as part of the texture vouchers, i helped newcomers get started, i farmed, i fished endlessly (got about 3 mending books, my personal highscore), I trained, i grinded the hours of my life away for nothing at the end. I even managed to join Unova, although my presence was rather brief.

So, what now? Well... nothing.
I'm done, that's all folks.

I suppose in the end, it shouldn't matter much. This is just a damn computer game. All of these items, the progress i made? None of it truly matters in the face of reality.
But, there is something i still can do.
To all those worthy, to my fellow members of Unova... My base and it's treasures are yours.
That's right, all of my goodies, if you can find it... It's all yours that is if Ras or his staff haven't decided to demolish the place. It's likely that the few souls who even see this outside of them may not find it. But it will be found eventually. It'll all be yours. The clock is ticking until my claims on the base expire, when that happens, take whatever you want. If you'd like, you may build a statue of me and Soxiel (The last person i tried to help) in remembrance.

If your staff (Which you likely are.) don't spoil the fun. It's not worth it. You'll only make yourselves look worse than you already do.

You're probably wondering, why aren't i putting up much of a fight? Well, there isn't much to my defense here, my defense might be solid, but again there isn't much. Besides, you all have already decided i'm the bad guy, that i'm a griefer. No matter what i say, i cannot dissuade that opinion of me. I won't try.

That's it, i have nothing much left to say.
But, it'd like to address a few people.

First, to Rasgnarok: Hey pal, no hard feelings right? I won't hold anything against you. It's your server, you have the ultimate say on how anything goes, that's fine with me. If we walked past each other on the sidewalk i probably wouldn't bat an eye at you. I'll continue my work on the textures, next is Primal Dialga? I'll let you know via discord dm's (If you haven't blocked me) if i make any progress. After all, the very reason i started working on those was because of my disgust over Nintendo's shiny selection (I mean, a darker/sickly green snivy just ain't gonna cut it.) I wanted to make new designs people liked, and that i liked. That won't change.

Second, to You. The readers, the players of Oblique: I hope you hold my memory dear, i hope you don't remember me as the guy who was apparently a griefer, someone who'd steal anything he'd come across. I won't think of you any less if you do, but can you say the same to me?

And finally, to the Griefer: I hope your happy, i hope it was worth it. I don't know how you did it, how you feigned your ip address to instead be mine, so you could steal from everyone in a computer game. I know your probably happy as can be, while i'm forced to leave, perhaps you'll lay low for a little while so you can start stealing from everyone else, and then frame someone else for the crime. I so badly want to congratulate you on doing so, you did it. You win. But that doesn't matter.

I might come back, who knows? If i ever find a spare 40$ or so, i'll think about buying a new account and rejoining you all. But for now, i'm leaving and rejoining the "Limitless" server. Maybe i can improve things there? If you happen to join me, i'd be happy to help you get started. Until we meet again.

Farewell, Oblique!

- HyperWilson

**Comment by Hiroku** [comment]
Cya

**Comment by AdmiralCrunch56** [comment]
Thank you for making my night at work. This has to be some of the best shit I've seen. Bravo.

**Comment by Hiroku** [comment]
For those who might come looking through here and think that Hyper might be anything other than a liar who got caught with his hand in the cookie jar, there is absolutely no way to fake an IP address as someone else's. It's just not possible. He used an alternate account to rob his neighbour thinking he was being really clever, but unlike most people with alts he didn't even change his IP.

To any other griefers that are reading this, please be as easy as this guy.
