### ISSUE TITLE
I've said what i've needed to say.

### ISSUE THREAD

**Issue by HyperWilson2** [ObliqueNET/Terra#396]
"You: "I want a statue built in my honour"
Also you: "It's just a Minecraft server ha ha ha"

You: "If you silence me, it means you're* afraid of what I have to say"
Also you: "Someone somehow used my IP! I'm innocent! I don't know how it happened!"

Reason why you're getting banned from this tracker is because you keep making tickets where you attempt to profess innocence and righteousness when you got caught like an absolute muppet. I'm quite happy for you, and whoever somehow believes you, to leave. We'll see how long you remain on Limitless. The owner of Limitless and I made the mod, so I'll get him up to speed real quick."

I never demanded a statue built in my "honour" as you describe it, i simply asked if some sign or monument may be erected for that one guy as well as the person who's practically giving them a bunch of shit to remember me by, i don't see anything wrong with that. Yes, it is a GAME you do whatever the hell you want to in a GAME. Minecraft is all about that correct? You can build houses, statues, air balloons, you name it. It's all up to your imagination.

Also, how does silencing me and someone copying my ip address correlated? I missed that part of your logic. Still locking my threads, still banning me (Banned from discord) proving my point.

Stop acting like a damn king. You're a king residing in a virtual world, take a look around you "muppet", you shouldn't be so prideful. You've made yourself look like a complete asshole, and here i am trying to explain otherwise, here i am giving you a different opportunity to address me with some class. 
And you threaten me by going to Jay and complaining to him that i said some "mean" things on your tracker? Why should he care about what happens in YOUR server? You've banned me, good job, you make yourself look impish by acting so entitled. You can't just get rid of me because you don't like what im saying, i'm sure Jay could care less whether or not something happens in YOUR server YOU have full control over! I'm still making those textures btw, so if you see Ras, tell him to unblock me so i can update him on my progress.

As for this whole fiasco, i feel i've said enough. Please. DONT Respond back. I know you would like to twist the story to make me the "Bad Guy" and all. But please, don't make any more a fool of yourself than you already have, with time this will all pass over our heads. I'll buy a new account or something, and i'll play some pixelmon with you all once more eh? Maybe that time around... I'll finally get my 6IV Snivy. One day, we will all look back at this garbage and laugh at it. I await the day i'll get to join ya'll again. Until then, please sit back and relax. It's been a long day, people need to sleep. And Hiroku, please have some decency, sit back and take a break.

**Comment by Hiroku** [comment]
You keep telling me that I need to relax and take a break but you're the one writing literally hundreds of words in an issue tracker, making new accounts in an attempt to get the final word in, and desperately trying to belittle the man that made the mod you're enjoying. Talk about having decency, lmao. Have some respect, take responsibility, and face consequences like an adult.
