### ISSUE TITLE
Proken Nidoking

### ISSUE THREAD

**Issue by ZackieKun** [ObliqueNET/Terra#397]
So I had a HA Nidoran M (Hustle), evolved it into a Nidorino, still had Hustle which is a-okay, used my moonstone to evolve into Nidoking.... and it still had Hustle... When its supposed
![NidoKing Bug](https://user-images.githubusercontent.com/56382047/66544093-c1777380-eafc-11e9-8c5d-726e71e3b4b7.png)
![NidoKing bug2](https://user-images.githubusercontent.com/56382047/66544094-c1777380-eafc-11e9-9290-99f7d234b533.png)

 to be Sheer Force.

**Comment by Vohras2** [comment]
Fixed.
