### ISSUE TITLE
Ban Appeal

### ISSUE THREAD

**Issue by AhmadAradii** [ObliqueNET/Terra#399]
Hello,

I was trying to enter the server today since i wasn't online for like a week i guess and i got banned saying that i was stealing which i don't even remember doing that the only thing that i can remember is when i find someone's base and it's not claimed i put a sign to tell them to claim it that's all. So i don't know what should i do now with this issue here.
![Banned](https://user-images.githubusercontent.com/23116613/68183362-44310880-ffad-11e9-91d3-6be732542f0f.PNG)

**Comment by ElementalMP** [comment]
You were banned for stealing from player bases after being warned previously for the same offense. As for the claim of not taking anything, we have logs with your name on it ¯\_(ツ)_/¯

**Comment by Rasgnarok** [comment]
Closing this appeal as it is now almost a month old.
