### ISSUE TITLE
Why did i get banned

### ISSUE THREAD

**Issue by OVmaster123** [ObliqueNET/Terra#401]
I got banned for xray For no reason i never use xray and some how i got banned for having 6 stacks of diamonds So i my user name is OVmaster123 i would like a answer
 
![2019-11-07_21 14 26](https://user-images.githubusercontent.com/57310974/68451444-a5223180-01a3-11ea-94aa-41a4fc813b1a.png)

**Comment by ElementalMP** [comment]
You were banned for directly digging down through multiple layers of stone to diamonds, and amassing 7 stacks of diamonds, while attempting to sell them to players in exchange for money.

**Comment by Vohras2** [comment]
Over a month with no reply. Closing.
