### ISSUE TITLE
Please unban me

### ISSUE THREAD

**Issue by babydirty20** [ObliqueNET/Terra#402]
Hey admins, I am very sorry for what I have done. Due to how often I afk, I did not receive any warnings regarding a ban. Had I known I received a warning I would have stopped, I also promise that I will not lie to any of you again. I promise that I will change, all I want to do is breed pokemon and have a fun time on your great server, breeding pokemon is my dream job and I was always told by my parents to follow my dreams. I promise that this won't happen ever again, if this does not satisfy you, at least ban me for only a week or a month. I am a single father of 2 kids and pixelmon is the only thing that keeps me going, my wife left me only a few months ago and this is my only escape. My dad is suffering from lung cancer and the doctors say he only has 3 months left, I want to make sure that he dies knowing I followed my dreams.

Thank you in advance, babydirty20.

**Comment by BlitzAsogi** [comment]
If you wish to appeal, please do so without making an article sound like it comes from the onion.
