### ISSUE TITLE
Banned

### ISSUE THREAD

**Issue by Steevie88** [ObliqueNET/Terra#406]
I just got Banned for "still stealing from unclaimed Bases", which I didn't do again after the first Ban. 
I was just transporting building materials from my Base to my Outpost (both my claim).

**Comment by ElementalMP** [comment]
I'd like to believe that, but it seems the server logs indicate you clearly taking from another base, which doesn't belong to you. Any idea how that would come about?

**Comment by Vohras2** [comment]
Been over a month. Closing.
