### ISSUE TITLE
[Bug] Quests at_time 

### ISSUE THREAD

**Issue by Rasgnarok** [ObliqueNET/Terra#408]
```   stage=2
    {
        {
            description=Talk to Xuman in the day
            hint=He said at night u dum dum
            timestocomplete=1
            hidden=True
            infinite=True
            conditions
            {
                at_time(flipped=True;time=night)
            }
            type=chat_npc(uuid=60443dcf-1756-4fe5-8a94-e6aa3b2449b7;chatline1=It’s still pretty bright out, and I haven’t seen any signs of the raiders yet.;chatline2=Why don’t you have a look around first? Its that big green building down there.;chatline3=Spend some time looking around tesla too, it’s a pretty good town, despite the evil-doers.)
        }
        {
            description=Speak to Xuman at night
            hint=He’s atop the hills behind Nemalabs.
            timestocomplete=1
            hidden=False
            infinite=False
            triggers
            {
                skip_to_stage(delay=0;stage=3)
            }
            conditions
            {
                at_time(flipped=False;time=night)
            }
            type=chat_npc(uuid=60443dcf-1756-4fe5-8a94-e6aa3b2449b7;chatline1=You ready for this partner? This one is going to be slightly rough.;chatline2=The raiders managed to make their way inside via a traitor in the Nemalabs staff, but we don’t have that luxury. Otherwise, an alarm would have went off.;chatline3=However, you have me on your side!;chatline4=I will be able to delay the alarm from reaching the guards for 2 minutes maximum, so you’re going to have to find the alarm panel by then.;chatline5=I will be on standby for the alarm, so just run in whenever you are ready.)
        }
    }```

**Comment by Rasgnarok** [comment]
Removing the at_time=night flipped=false allowed for progression. Looks like the check for the day at_time worked the whole time however.

Theories: at_time night specifically, second stage objective, condition flipped=false... or just at_time flipped false?

**Comment by Rasgnarok** [comment]
[12:12 AM] ☘ Stride ☘: oo snap
[12:12 AM] ☘ Stride ☘: i didn't see the ping sorry @Ras i ended up completing it
[12:13 AM] ☘ Stride ☘: i just spammed him and it progressed at a certain time i don't remember tho

Maybe 'night' isn't well defined?

**Comment by starwarschamp4** [comment]
Just to test, re-uploaded the old Halloween Ione that requires it to be night, and it worked fine when it was and didn't when it was day. Here's the code from it.

conditions
            {
                at_time(flipped=False;time=Night)
            }

**Comment by Valjean42** [comment]
Gonna try to look into the code of it (as well as some other quests' conditions) once i get on my computer, in about 30 minutes. Meanwhile maybe try Night with a capital N? That seems like the main difference here, even though it mostly shouldnt matter

**Comment by Valjean42** [comment]
![image](https://user-images.githubusercontent.com/47981683/69316918-75166c00-0c42-11ea-8127-9a7487fa5f5b.png)
weird, seems the condition on its own works for me... Ras, can you send me the full file on discord? (@valjean42#9680)

**Comment by Valjean42** [comment]
Ok so i found the bug in the code, fixed it and sent it to hiro. the problem was a function which searched for only one objective of a specific type, instead of all of them, which made it so it ignores everything after the first objective in some cases.

**Comment by Hiroku** [comment]
Valjean's fix checks out, closing this ticket. Be sure to send Val your thanks
