### ISSUE TITLE
Ranch Breed compatability oddness

### ISSUE THREAD

**Issue by Toby-Wilson** [ObliqueNET/Terra#411]
Ran into an instance of trying to breed eevee (M) with minun (F), they are field and fairy egg groups respectively so shouldn't (and don't) breed - however the pokemon models in the ranch were reporting them as being attracted to each other when right clicked - indicating that they can (displayed the affection growing rapidly message on both)

**Comment by McConnell2111** [comment]
eevee is field breeding group and minun is fariy they need to be in the same egg group for them to breed. use this is find another male to breed it with. in game you can also do ./wiki (pokemon name) (egggroup)  https://bulbapedia.bulbagarden.net/wiki/Fairy_(Egg_Group)

**Comment by Toby-Wilson** [comment]
^ Yeah I know - the bug was pertaining to the ranch (when clicking on the pokemon in it) saying that they were attracted to each other when it should have reported they were not interested due to differing egg groups

**Comment by Vohras2** [comment]
This is more of a pixelmon issue. Report to them instead.
