### ISSUE TITLE
Server not loading and totally unplayable

### ISSUE THREAD

**Issue by plasmarob** [ObliqueNET/Terra#417]
This is the second evening my wife and I (Stormy_DLoA & plasmarob) have not been able to get on the server. It cleared up a little after well over an hour of trying last night.
It sometimes boots us to the entry world and says something about proxy servers failing.
Update: happened once more, here:
"The server you were previously on went down, you have been connected to a fallback server"

Any idea what's going on? It's nothing on our side - well managed high speed internet/ram/disk and i'm monitoring the traffic, we are behind in the chat by as much as 2 minutes.

**Comment by starwarschamp4** [comment]
This has been happening to me too actually, chat gets behind by a minute and after a while I crash. I'm using Forge, don't know about you. Hope it gets resolved.

**Comment by plasmarob** [comment]
I am using Forge - We've always used the Technic Launcher.

**Comment by Rasgnarok** [comment]
I need all of you to add your debug.log of your most recent attempt. I am trying to diagnose this, but as luck would have it, there is not a lot of data that MC sends the server regarding connection latency. I'd also need a rough timeline of when it started to happen.

On my end, I am going to reach out to a couple devs whose plugins/mods we use in the hub.

**Comment by plasmarob** [comment]
I've noticed it's happening again right now, i'll see if i can get the proper logs. It seems to be happening between 8pm and 10pm my time (mountain /MST) independent of whether it's weekdays or weekend. It  often clears up after that.

**Comment by plasmarob** [comment]
[2019-12-04-logs.zip](https://github.com/ObliqueNET/Terra/files/3937856/2019-12-04-logs.zip)
Logs (3 files) from the day I opened this issue

**Comment by plasmarob** [comment]
[debug-5.log.gz](https://github.com/ObliqueNET/Terra/files/3937859/debug-5.log.gz)
This is the best debug.log i have for now as far as i can tell, next time it's definitely happening i'll send the debug.log immediately

**Comment by Rasgnarok** [comment]
![image](https://user-images.githubusercontent.com/18584380/70407326-dfd0f100-1a11-11ea-9fef-d4e34b818d5d.png)

Okay, this is pretty standard of an error, but it really seems to mimic what I found also in the hub logs. I think I am definitely looking at a bungee issue now, and I think it's starting with our first host (which carries the hub), not the one that hosts Terra.

**Comment by plasmarob** [comment]
I literally work on systems like this for a living, and though I'm not familiar with your setup, bungee etc, I can tell you all my suspicions agree with you.

It is indeed as bad with the first/core and not only Terra, and I guessed bumgee also.

If it adds a clue, I have noted on more than one occasion that the first/hub had the lag problems at times while Terra was working fine. (to restate for clarity, if Terra had problems the first always did too, but the first can have the problems without it affecting Terra)

Thanks Ras you're amazing.

**Comment by plasmarob** [comment]
If you like, I can run some times tests, I used to be a QA engineer. the behavior is like clockwork, like a script, and we go from excellent connection to terrible and back near instantly, independent of server activity.
It makes me wonder if part of your system is getting DDOSed by a bad actor at peak times.

**Comment by Rasgnarok** [comment]
Interesting timing. Frankly, I would not be surprised if it was, but feel free to DM me so we can discuss this in a bit of a less public setting, there's some more info I need to hold out because we do have people that have reasons, and resources, to DDOS us. It also very well could be some overload on Bungee's parts, I can't say I am the most skilled with it. 

Ideally, I'll have to call directly OVH and see if they can diagnose the setup, which likely will have to happen once I finish finals (for instance, 2 papers, 1 final tomorrow at 9AM).
