### ISSUE TITLE
Banned

### ISSUE THREAD

**Issue by qtgay12** [ObliqueNET/Terra#421]
I'll admit I did steal from unclaimed bases, but none today. If I were to be unbanned I would no longer do this thanks, and i returned pretty much everything already. Thank you
IGN: qtgay

**Comment by ElementalMP** [comment]
That's very noble of you, admitting to previously stealing. Unfortunately, logs would show that you have actually stolen more items today, in fact less than an hour from your ban? I find it strange that part of your appeal is truth, and the next part seems to be a direct lie, and correct me if I am wrong, but that seems to be the case here.

**Comment by qtgay12** [comment]
Im sorry, I guess i got a bit to carried away with the items I took, if I get unbanned i will return the items i stole that day, and it wont happen again. thank you

**Comment by ElementalMP** [comment]
Solved in DMs ^
