### ISSUE TITLE
Preserving Claims

### ISSUE THREAD

**Issue by PrimalCyndaquil** [ObliqueNET/Terra#425]
Idea: If a player has their account linked to Discord, they should be able to directly message Mia/Eli with the following phrase:
"Please preserve my claims for the next <max 30d>."
This will then put the player in a list exempting them from rollbacks or claim deletion.

**Comment by ElementalMP** [comment]
Claims already last 30 days before decaying, so it's a little redundant to have Mia make them last anything less :p

**Comment by Vohras2** [comment]
They last 60 days, iirc. He's saying he wants to extend the max time by 30d by running a command through Mia.

**Comment by Vohras2** [comment]
This has been added, and should (hopefully) work. Closing.
