### ISSUE TITLE
Multiple duplicate pokemon returned from marketplace

### ISSUE THREAD

**Issue by byuiwriter** [ObliqueNET/Terra#428]
I put a single Shuppet in the marketplace and it was returned to me because no one bought it. On Dec 29 I received a total of 7 messages at 3:32, 3:42, 4:10, and 4:33pm stating the Shuppet was returned. I was unable to access my computer until later on Dec 29 and found I had 7 duplicate Shuppets in my inventory. All are identical and when I throw out one the side panel shows that all are out. I was able to add the same Shuppet to the marketplace on Dec 30 at 11:56pm; however, the duplicates are still in my inventory in game.

[debug.zip](https://github.com/ObliqueNET/Terra/files/4012092/debug.zip)
[latest.zip](https://github.com/ObliqueNET/Terra/files/4012093/latest.zip)

![2019-12-31 (1)](https://user-images.githubusercontent.com/59384954/71613126-c2e79380-2b61-11ea-9168-4df8fba3a3da.png)

**Comment by Hiroku** [comment]
This was a consequence of a bunch of issues that were going on at the time and has been fixed. Pls dump the excess pokemon, thank
