### ISSUE TITLE
Ranch Block glitch

### ISSUE THREAD

**Issue by Nattryon** [ObliqueNET/Terra#434]
I took my Miltank out of the ranch block, but it’s still standing in the ranch area and I’m able to interact with it even though there are two other Pokemon in the ranch block. I’ve tried relogging and breaking and replacing the ranch block, moving it to another spot in the pc and putting it in my party but it’s still there. It doesn’t seem to be interfering with anything so far, but I’d like for it to go away. Any suggestions?

**Comment by qnom** [comment]
A Staff member (helper+) can help you with that by unlocking your ranch blocks. This will reset ALL ranch blocks you own though, so remove any eggs you have before you ask for help.
