### ISSUE TITLE
Grass rustling tries to use eggs in double battles

### ISSUE THREAD

**Issue by Blastblaze1** [ObliqueNET/Terra#435]
Hello! With the new rustling grass feature, I found that if you have an egg in the second slot of your party and another pokemon in the first, running into a rustling grass patch that would start a double battle will send out the mon in the first slot as the first in battle and, weirdly, the mon in the egg as the second, and then freeze with the waiting glitch without spawning the 2 wild mons. After using /endbattle, the mon that was in the egg remains out of battle and can't be returned to the ball unless you relog, put it in the PC/Healer, or wait until it hatches.
![RustlingEgg1](https://user-images.githubusercontent.com/50856203/72751452-4acf2500-3b85-11ea-9a13-8e6a82e9e56c.png)
![RustlingEgg2](https://user-images.githubusercontent.com/50856203/72751465-50c50600-3b85-11ea-8134-976948876169.png)

**Comment by Valjean42** [comment]
Yeah, while making the plugin i did not take that into account. I solved the issue and updated the files on my side, i will send them to ras/hiro and the changes will probably be implemented soon, most likely on the next restart.
