### ISSUE TITLE
"The Electric Demon" not completing.

### ISSUE THREAD

**Issue by Blitzmentalist** [ObliqueNET/Terra#437]
Making a note here so we don't forget.
Upon catching the Rotom at the end of the quest, the quest disappears from the Quest book and becomes stuck on Stage 14. This error has occurred three times in a row, and manually adjusting the steps does not fix it.

**Comment by BlitzAsogi** [comment]
This quest has been fixed, the specs wasn't set up right to spawn a rotom heat, which was what the quest was checking if you caught
