### ISSUE TITLE
Ban Appeal

### ISSUE THREAD

**Issue by Smithy2116** [ObliqueNET/Terra#438]
I would like to say im so so so sorry for continuing. I shouldnt have done it and i reget my mistakes. The server is class and I had a lot of fun playing on it, even if i did slightly annoy the staff. If you give me one Chance then I would greatly appreciate it, please!

Username: Smithy3

**Comment by ElementalMP** [comment]
I will unban your account, but know that second chances seldom come around, and you won't be receiving another warning.
