### ISSUE TITLE
Ban Appeal

### ISSUE THREAD

**Issue by JakeFordo** [ObliqueNET/Terra#440]
Hello,

I am going to try this through here since my last attempt at explaining the situation failed. A few years ago, I joined Oblique and fell in love with it. I donated, and even became a Helper and a Gym Leader. I loved the community and loved being a part of it. On the side, I have owned and co-owned smaller servers. I paired with a guy who came to me to help create a server. We created this server, and sadly it fell due to various reasons. This individual then added me to a random unnamed Discord group with a few other people that I was unfamiliar with. He then proceeded to add Rasgnarok to the group. Once he did that, he quickly renamed the group “PokeRadar” (or something of that nature, as it was quite a while ago and the name slips, but you understand the idea). I am then banned from Oblique for “PokeRadar Use” after never even using the mod, let alone getting on Oblique with the mod. I was wrongly accused of something that I did not do simply because I was tricked into joining a Discord server. I was never suspect tested on the server, nor was I ever given the time by any staff of Oblique to explain myself. Since then I have moved on, but still have wanted to play on the server and would like to enjoy my time on there again, so I thought I would try and explain my story again and hope that someone will listen to me.

Thank you.

**Comment by Rasgnarok** [comment]
![image](https://user-images.githubusercontent.com/18584380/73993020-ff579d80-491e-11ea-947d-84bda2063ee6.png)

You'll have to DM me if you want on Discord, because from what I see of our DM conversation, there's lots to explain.
