### ISSUE TITLE
Pixelmon Reforge isn't opening on Technic.

### ISSUE THREAD

**Issue by GodLucy** [ObliqueNET/Terra#442]
I've been trying to get on just to keep my claims but ever time i get on it's giving me an error saying something is missing. I took a screen shot of it and posted it in the wrong discord.. (Opps), and thought i'd just post here for now. I've tried reinstalling the mod multiple times with the same error showing up. 
![reforge error](https://user-images.githubusercontent.com/61065734/74565067-fb86d500-4f35-11ea-89e4-11b8e07736b7.png)

**Comment by Vohras2** [comment]
Not sure what could be causing that on Technic, but have you tried our specific pack on Technic? Apex Pixelmon. You could also use AT Launcher to download the official pixelmon pack.

**Comment by GodLucy** [comment]
ill have to find them then. I haven't tried them before because Technic worked so well with me.

**Comment by Vohras2** [comment]
https://www.technicpack.net/modpack/apex-pixelmon-reforged.1449772
https://atlauncher.com/downloads

**Comment by GodLucy** [comment]
well the other technic pack did the same thing, Im gonna try the atlauncher now.
![error 2](https://user-images.githubusercontent.com/61065734/74595476-4886ac00-5007-11ea-9c6c-1c4cd4bdc0c0.png)

**Comment by GodLucy** [comment]
ATLauncher worked just fine, thank you!
