### ISSUE TITLE
Some Quests Needing Fixes

### ISSUE THREAD

**Issue by Lieren-HuntGhosts** [ObliqueNET/Terra#444]
Also, when reach step 18 of "A Sparkling Mutation" (once the carbink is a diance now) there's no "leave the zone" condition, making it impossible to return if you leave and dont have the /back
Imma post this and the Avenging Flames error on github so we dont lose them

There seems to be a problem with the quest "Avenging Flames", in which an overlap of the dialogue when being defeated, the tp and the battle itself seems to be causing 3rd Person Camera Locking
Could be easily solved if just adding some time for the dialogue and then the TP out. The combat with Menma is stage 7.

Quest "An Unexpected Delivery" should be Vulpe, not Oxus guild requirement.

"Human Nature", After losing to or fleeing from the mewtwo boss it teleports you to -480 66 -1259, which is underground and you suffocate. Also after speaking to the Guru in that step after losing/fleeing, It returns you to step 12, which is healing in the lab, repeating the dialogue there of getting a MBall, this doesnt make much sense since you are coming back to try to stop mewtwo, you didnt travel back in time.

**Comment by BlitzAsogi** [comment]
Sorry i forgot to comment about this, but they have been fixed since
