### ISSUE TITLE
Discord Ban Appeal

### ISSUE THREAD

**Issue by clampert1** [ObliqueNET/Terra#449]
Am a new player! :). I joined discord but got immediately banned by a discord bot named "Apollo" "You are being removed from the Oblique Discord because I'm pretty sure you're one of the raid bots. If this is in error, say so at https://github.com/ObliqueNET/Terra/issues" so now I'm here to prove im not a raid bot and to get unbanned from the discord!!... My discord is clampert#1731

**Comment by qnom** [comment]
What is your Minecraft username?

**Comment by clampert1** [comment]
clampert

**Comment by qnom** [comment]
When did this happen? I'm not seeing anyone by the name clampert that joined the server.

**Comment by clampert1** [comment]
24 minutes ago

**Comment by qnom** [comment]
Woops, thought you meant the pixelmon server. Elemental is gonna take over for me anyways. He can help you.

**Comment by clampert1** [comment]
ty!

**Comment by ElementalMP** [comment]
Damn, Apollo really do be on that raid defense grind. I think it's pretty obvious here that you are in fact, not a bot, so I'll unban you from the discord. Sorry about all the inconvenience!
