### ISSUE TITLE
Claimblocks Kits Gone. People say they dont retrieve Claimblocks.

### ISSUE THREAD

**Issue by Suljia** [ObliqueNET/Terra#48]
I got today reports of people saying they ranked up and got no Claimblocks, there is confussion as the kits are gone.

https://cdn.discordapp.com/attachments/401570956780240899/401571074917269505/Kits.png

Suljia - heute um 04:02 Uhr
hmmm did you check if you have more claimblocks ?
all the claimblock kits seem to be gone
RegulasKA - heute um 04:03 Uhr
yeah i have the same amount as i did when i was Great rank

He is Ultra Rank and claimed the regular Ultra Rank kit

**Comment by IceColdRamune** [comment]
World_Child

Yeah, same thing happened to me when I went from ultra to dream.
Will we get the claim blocks later? thanks.

**Comment by Kitsune30** [comment]
Yes, you will get the claim blocks for sure, but for now just wait.

**Comment by Kitsune30** [comment]
You now get claimblocks upon rank up, For now you will have to log out and then log back in for them to show up. I'm going to work on a way to make that not necessary, but you do have them for sure now.
