### ISSUE TITLE
List of unsellable mail.

### ISSUE THREAD

**Issue by ServantGirl** [ObliqueNET/Terra#49]
I will update this list any time I notice a mail cannot be sold.

Favored 
Glitter
Dream
Inquiry
Fab

-----
Steel

**Comment by ServantGirl** [comment]
Added mail.

**Comment by Kitsune30** [comment]
Can you find their pixelmon:<name> names and add them to the sides?

**Comment by Kitsune30** [comment]
So it looks like once a mail is opened it becomes unsellable. For now just don't open any mail you intend to sell.
