### ISSUE TITLE
Dexranker - Premier Grouping Mismatch

### ISSUE THREAD

**Issue by NickImpact** [ObliqueNET/Terra#5]
It appears as if the Premier rank for Dexranker is now referred to as Other. My guess, being likely due to the fact that Premier is referred to as default now in LuckPerms. Believe a server restart is in order to fix this LP side, so a ticket was made for the next possible convenience.

I'd fix it, but its 4 am so back off!

PS: Give me powers here!

**Comment by Kitsune30** [comment]
To add, manually pushing someone along in LP does not fix the issue. Does Dexranker store and internal list of what people should be at, kept separate from LP data?
