### ISSUE TITLE
Quest Issue

### ISSUE THREAD

**Issue by HavePatience5** [ObliqueNET/Terra#50]
IGN:HavePatience
OK, so the quest in Tesla with the scientist that tells u to enter a machine does not work for me. The minimum quest points needed are 30 and I have 30 yet it still doesn't let me start the quest, you're supposed to talk to the scientist to start it but it doesn't start for me.. I did start this quest when I had 25 points only idk if that was an error or something because when i started it the name of the quest was "requiredquestpoints=30" then it disappeared from my quests later and now that I have 30 quest points and I go to start it again it doesn't start all the Scientist says is "Hello fella"

**Comment by Kitsune30** [comment]
Can you give the coords that the NPC is at so Quest Designers can better assist?

**Comment by Soshisen** [comment]
I'd still like to know where this was
