### ISSUE TITLE
Non-quest trainers with incorrect battle schedules

### ISSUE THREAD

**Issue by ServantGirl** [ObliqueNET/Terra#51]
This post will list trainers whom can only be battled once or once per day as opposed to once a minecraft day.

As I understand they're all meant to be once a Minecraft day, unless part of a quest or a boss. 

If (Probably when) I find more, I will update the post.

66, 73, 547 Blue jacket near Tesla- Can only be battled once per irl day
54, 72, 607  Scientist- Can only be battled once per irl day
20. 72, 637 Just up the road- Can only be battled once per irl day
-118, 67, 725 Fire dude- Can only be battled once per irl day
-166,  67, 748 Right near fire dude- Can only be battled once per irl day
-245, 66, 797 Rocket grunt- Can only be battled once per irl day

**Comment by Kitsune30** [comment]
Since this is so old and we havent received any reports recently, I'm going to close this.
