### ISSUE TITLE
Lopunny's ability is its mega's

### ISSUE THREAD

**Issue by BlitzAsogi** [ObliqueNET/Terra#54]
![image](https://user-images.githubusercontent.com/24644181/35184985-b3e106d6-fe37-11e7-9a7e-667737a26c26.png)

I also checked it with pokesee, ability is still listed as scrappy

**Comment by Rasgnarok** [comment]
eg, Lopunny keeps the mega-form's ability after evolving and out of battle. Data concurs. Reporting to Reforged.

**Comment by Kayouri** [comment]
https://gyazo.com/c4095a8a0a6a046dfe0ea7386aaac967
Lopunny using Return successfully on a Gastly - It has Scrappy as its normal ability, and it's working.
(Had a Buneary with Run Away, and evolved it, and it ended up having Scrappy as its evo. ability)

**Comment by Rasgnarok** [comment]
Fixed
