### ISSUE TITLE
Patrat shiny sprite glitch

### ISSUE THREAD

**Issue by Strikdalic** [ObliqueNET/Terra#55]
Ola Migos, Just caught a shiny patrat and the eyes are glitched or bugged, shinies are suppose to have blue and yellow eyes but they still have the normal eyes, just a heads up, be great for a lil fix 😄 
![2018-01-21_18 57 34](https://user-images.githubusercontent.com/35655041/35193486-137f3d28-fede-11e7-8f27-da6cdc7b9c2c.png)

Also there's little things sticking out the eyes.

**Comment by Rasgnarok** [comment]
Fixed for an upcoming version, I hear.
