### ISSUE TITLE
Sprite issue with Mewtwo

### ISSUE THREAD

**Issue by BootiesMcGoo** [ObliqueNET/Terra#57]
Hi, i have a bit of an issue with my mewtwo as it is very small, the nametag is floating way above him. Its size is ordinary and when i ride it i float above it
![capture](https://user-images.githubusercontent.com/35689246/35218373-871fa63e-ffc2-11e7-821f-d9ce666a1a47.PNG)

**Comment by Rasgnarok** [comment]
Closing, I hear it's solved for next version.
