### ISSUE TITLE
Ash-Greninja

### ISSUE THREAD

**Issue by Suljia** [ObliqueNET/Terra#59]
I got several reports of players with a "bugged" ash-greninja and i was fishing the last days for over 10h.

I finally got a Greninja fished up and my Trace Gardevoir immediatly messaged me "traced Torrent." I ran away from the fight as i thought it was not worth it only to find next to me a wild "Ash-Greninja" walking around.

I caught it and the Ash-Greninja is stuck in its Ash-Greninja form, has the Ash-Greninja Spire and Statboost -Permanently-.  It came with the usually undiscovered Egg group 3x31IVs but with the Torrent Ability.

https://imgur.com/a/1tzSI

Stats from a lvl 49 regular Greninja i caught to comparsion

https://i.imgur.com/RednMQW.jpg

Update:

How it looks to me after testing.
Every fished up "normal" greninja is currently a bugged Ash-greninja. It is permanently and bugged.

The Battle Bond Greninjas are rare and working as intended i cant find any bug with those.

**Comment by Suljia** [comment]
Update:  I did mess up taking screenshots. However i found atleast 3 Bugged-Perma-Ashgreninjas in the wild over the last 2 days. All the same characteristics as the fished ones. They spawn naturally in swamps right now.

**Comment by Suljia** [comment]
Update2:  Normal Ash-Greninjas with the battle bond ability will stay in Ash-Greninja-form if they survive the battle as Ash-Greninja.  (Tested only in battles against other players)

**Comment by Rasgnarok** [comment]
Fixed for next version apparently.
