### ISSUE TITLE
Trainer Bug

### ISSUE THREAD

**Issue by TwinkerBell** [ObliqueNET/Terra#6]
I wanted to battle this Police man on the way to Agni, but was unable to battle him even though I just logged on and did not batter him yesterday. Just something i noticed.
![2017-12-27_12 05 56](https://user-images.githubusercontent.com/34893828/34388138-f7f806b2-eaff-11e7-87cf-27bde2221524.png)

**Comment by Kayouri** [comment]
This is being reviewed, for now I have been slowly replacing the battling and shopkeeper NPCs that do not work. 
If you could, PM me coords if you find any NPCs like this.
