### ISSUE TITLE
Goomy turning into wingull

### ISSUE THREAD

**Issue by BootiesMcGoo** [ObliqueNET/Terra#60]
Hi there, i noticed that one of my goomys disappeared out of box and brushed it off as i thought i wonder traded it, i now believe that the lost goomy and now this one turned into wingull somehow. I don't think a level 8 wingull is supposed to know dragon type moves 
![badgoomy](https://user-images.githubusercontent.com/35689246/35425748-987bbdb8-02b1-11e8-89c6-c56d9b1a6625.PNG)

**Comment by Kayouri** [comment]
Come to me in game and I can give you a new Goomy, as for the bug, I am pretty sure Pixelmon knows, they just can not get it to replicate, so they can't fix it.

**Comment by Rasgnarok** [comment]
https://github.com/ObliqueNET/Terra/issues/76
https://github.com/ObliqueNET/Terra/issues/71

All of these are storage issues, Reforged is planning on a re-write. I am keeping this ticket up to pile in all known ways it can mess up, closing the other tickets.

**Comment by MattBlower** [comment]
fixed long ago so can be closed
