### ISSUE TITLE
Clefairy and Clefable models/shinies

### ISSUE THREAD

**Issue by KingSentry** [ObliqueNET/Terra#61]
Clefairy and Clefable really need new models and their shiny to be fixed. they always look slightly like an orange boss as they have a very orange tone to thm which they shouldn't have. this problem has been around a while but I would love it if these could get some attention in an upcoming update, ty

**Comment by Kitsune30** [comment]
So this is a modeling issue, which means we need modelers :P 
If you want to learn how to mode, you could help Ras get better ones into the game.

**Comment by Rasgnarok** [comment]
Not a bug, closing.
