### ISSUE TITLE
'EV reducing' berry trees

### ISSUE THREAD

**Issue by Kayouri** [ObliqueNET/Terra#62]
It looks like Hondew, and Tamato berries don't grow, or, grow very slowly - mine have gotten to the sprout phase while the other 3 berries have been harvested 3 times now. 

https://gyazo.com/b72331fb3254c4da5a49c905079f2296

**Comment by Kayouri** [comment]
It also seems that they only grow in specific biomes, like all grow in swamps - but I have seen Hondew berries naturally grown in my Birch Forest, and the ones I planted refuse to grow.

**Comment by Kitsune30** [comment]
Are they all under the same amount of lighting?

**Comment by Kayouri** [comment]
Each line of water has glowstone under it - so I am pretty sure ^_^

**Comment by Rasgnarok** [comment]
I am told they are supposed to be loaded for 12-20hours for them to fully grow. Not a bug, but probably should be changed sometime.
