### ISSUE TITLE
Mega Boosts not working (Alakazam)

### ISSUE THREAD

**Issue by Hawnty** [ObliqueNET/Terra#63]
During an advanced gym battle in Psychic, I was challenging TheDoctor420. We were on our last pokemon me with Alakazam (Mega) and him with Crobat. Now I lost because he out speeded my Mega Alakazam. Now originally I thought he was Scarf Crobat but he gave me proof that it was Choice Band. So I checked on Pokémon Showdown's Damage Calculator page and Team Builder page to recheck their Base Stats and Overall Speed stats. Mega Alakazam (As Lv100) gets a Base 150 speed where as Crobat gets base 130. Mega Alakazam has a Timid nature plus 30 IVs and 252 EVs in Speed to make the overall total 437 Speed. Doctor's Crobat has a Hasty nature plus 31 IVs and 252 EVs in Speed to make the overall total 394 Speed. In this case, he should not be outspeeding me without Choice Scarf. Here's the Showdown proof battle: http://replay.pokemonshowdown.com/gen71v1-696808266 and here are proof photos of the stats I used for the battles on showdown as well as the screenshots from TheDoctor420 to prove that he was not using Choice Scarf
![alaka](https://user-images.githubusercontent.com/35160163/35605980-9f23af02-06a0-11e8-917e-df454f58343f.JPG)
![crobat](https://user-images.githubusercontent.com/35160163/35606037-09850fda-06a1-11e8-9660-161c900da95e.png)
![crobat2](https://user-images.githubusercontent.com/35160163/35606057-2d767bfe-06a1-11e8-998b-d803760d5102.png)
![crobat3](https://user-images.githubusercontent.com/35160163/35606063-36ab0456-06a1-11e8-965b-f05a901da924.png)

**Comment by Rasgnarok** [comment]
Closing this one in favour of the general one, seems related.
