### ISSUE TITLE
Mega evolution speed brakets

### ISSUE THREAD

**Issue by ctproonie217** [ObliqueNET/Terra#64]
When a pokemon mega evolves they gain speed or lose speed but as i was testing my beedrill with 249 speed vs my brothers gyarados with 268 speed. When beedrill mega evolves he is supposed to go to 389 speed but he was still out sped by gyarados the turn after my beedrill out sped. So i was thinking maybe when you choose a move your turn bracket is predetermined so when you mega evolve you get the speed boost next turn.

**Comment by Rasgnarok** [comment]
https://github.com/ObliqueNET/Terra/issues/63 
Issues are related, leaving one open.

**Comment by Rasgnarok** [comment]
This should be fixed as of 6.2.1.
