### ISSUE TITLE
Gp Error when creating a claim

### ISSUE THREAD

**Issue by Th354ndman** [ObliqueNET/Terra#65]
The error code will show up instead of saying the minimum amount of blocks the claim must be in order to be claimed
![image](https://user-images.githubusercontent.com/29085055/36084967-1882db6a-1016-11e8-972e-40f44c7c98d4.png)

**Comment by Kitsune30** [comment]
Yeah it's a known issue, I think the plugin developer is working on it.

**Comment by Rasgnarok** [comment]
Should work fine now, we've updated. Closing
