### ISSUE TITLE
6.2 Sprites

### ISSUE THREAD

**Issue by BootiesMcGoo** [ObliqueNET/Terra#66]
Some of the sprites in 6.2 are messed up 
![image](https://user-images.githubusercontent.com/35689246/36192036-f565231e-11b3-11e8-8cca-0cf70fd5b4af.png)
![image](https://user-images.githubusercontent.com/35689246/36192039-fd921768-11b3-11e8-87ce-5a34e3ebdf3a.png)
![image](https://user-images.githubusercontent.com/35689246/36192051-0af71188-11b4-11e8-9bbe-4337d610c343.png)
![image](https://user-images.githubusercontent.com/35689246/36192070-18829822-11b4-11e8-8bf8-0bbc2d71f3a2.png)

**Comment by Rasgnarok** [comment]
This should be fixed as of 6.2.1.
