### ISSUE TITLE
Buged sprites 

### ISSUE THREAD

**Issue by NLXander** [ObliqueNET/Terra#68]
I found another poke with a buged sprite this time its Flabebe (in my PC) and my friend found a mauwstic with a bugged 1 #67 
![2018-02-14_12 50 27](https://user-images.githubusercontent.com/36476024/36203208-0ce6a396-1187-11e8-859c-6227171a44b8.png)

**Comment by Kayouri** [comment]
#66

**Comment by Rasgnarok** [comment]
This should be fixed as of 6.2.1.
