### ISSUE TITLE
Happiness Evos

### ISSUE THREAD

**Issue by Vohras2** [ObliqueNET/Terra#72]
Happiness evolution is supposed to require 220 happiness to happen. However, they are happening lower. I just had a Riolu evolve at 206 happiness.

**Comment by fatyg5** [comment]
If you could reproduce this, I'd be interested. Just tried in SinglePlayer with no way. Took 222 happiness on my Riolu to evolve.

**Comment by Vohras2** [comment]
I've been trying to reproduce without luck, so I dunno. Maybe it was a  visual glitch on my end and the mons were over 220 happiness at the time. I had been using a ton of berries, so maybe that's why.

**Comment by Rasgnarok** [comment]
Closing, ticket is outdated.
