### ISSUE TITLE
/wiki command

### ISSUE THREAD

**Issue by Th354ndman** [ObliqueNET/Terra#74]
Upon attempting `/wiki Vileplume Biome` I get this error

![image](https://user-images.githubusercontent.com/29085055/36799723-ed9548a4-1d01-11e8-9b69-9bcf40e7fcbf.png)

**Comment by Kitsune30** [comment]
This is a known issue between Pixelmon and Pixel Extras (where the /wiki command comes from.) Pixelmon changed some things on their end and Pixel Extras was not updated accordingly. Should be fixed soonish.

**Comment by MattBlower** [comment]
Updated and /wiki now works
