### ISSUE TITLE
Quest Bug - Completed Quest Step on Battle Forfeit 

### ISSUE THREAD

**Issue by FryFried** [ObliqueNET/Terra#75]
On the quest from Ion to Skadi with the Highwaymen - I forfeit the first battle since I knew I could not win but it gave me boss rewards (was fighting Volcarona) and put me on the next quest step. I was able to finish the quest after that without (what I assume was supposed to happen) battling the rest of the Highwaymen.

**Comment by Soshisen** [comment]
This is confirmed. New quest system overhaul will fix this issue
