### ISSUE TITLE
Catching pokemon occasionally results in duplicates and spam

### ISSUE THREAD

**Issue by BlitzAsogi** [ObliqueNET/Terra#76]
![image](https://user-images.githubusercontent.com/24644181/37328538-830c2970-26d5-11e8-9e92-0790fda45426.png)

All the Fletchlings have the same stats, IVs, natures and all.

**Comment by Kitsune30** [comment]
How many Fletchlings in total did you end up with and were they still present after a quick relog? Were they still present after a long relog?

**Comment by BlitzAsogi** [comment]
I cant say about the quick relog portion, but after logging out for about 2 hours, theyre still here
