### ISSUE TITLE
Mega Evolving shinies out of battle causes Sprite issues

### ISSUE THREAD

**Issue by BlitzAsogi** [ObliqueNET/Terra#77]
![image](https://user-images.githubusercontent.com/24644181/37337140-5ef86e9a-26ee-11e8-8920-545161ffc339.png)

Have tested with regular gard vs shiny gard, and also tested with beedrill & Pidgeot

**Comment by MattBlower** [comment]
This is due to their being no sprites atm for the shiny megas

**Comment by Kitsune30** [comment]
Originally reported here. #29
