### ISSUE TITLE
Ha vulpix not working

### ISSUE THREAD

**Issue by TheTrueLevi** [ObliqueNET/Terra#82]
So the hidden Ability of vulpix is not working in pixelmon or i am either using it wrong it does not proc when i send out vulpix

**Comment by Kitsune30** [comment]
Yes this is a known issue. It will be corrected when the server is patched.
They are currently working on the patch. I'll post here again when it is
patched.

**Comment by MattBlower** [comment]
should now be working in 6.2.3
