### ISSUE TITLE
Gyarados Ability does not match

### ISSUE THREAD

**Issue by BlitzAsogi** [ObliqueNET/Terra#83]
![image](https://user-images.githubusercontent.com/24644181/37516058-e78ef746-2947-11e8-865d-5cf7c947665f.png)

![image](https://user-images.githubusercontent.com/24644181/37516077-f280aa46-2947-11e8-9acd-0b5fe1601cc9.png)

My gyarados's ability is moxie, but at the start of the battle it shows the text for intimidate

**Comment by fatyg5** [comment]
Also fixed in 6.2.3 I believe
