### ISSUE TITLE
GTS stating wrong item returned

### ISSUE THREAD

**Issue by BlitzAsogi** [ObliqueNET/Terra#86]
![untitled](https://user-images.githubusercontent.com/24644181/38035413-f2f8efae-32d6-11e8-86ca-c0481e0b632e.png)

When placing an item in gts and removing it, it says Air is returned, but the item is moved into your inventory instead, and is not stated.

**Comment by Rasgnarok** [comment]
still reproducible with `GTS-3.6.1-S7.1.jar`

**Comment by Rasgnarok** [comment]
Closing issue because we finally got rid of GTS, yay
