### ISSUE TITLE
GTS not returning items with full inventory

### ISSUE THREAD

**Issue by GracieTheLatias** [ObliqueNET/Terra#88]
The GTS did not return my items (TMs) mainly when my listing expired with a full inventory. Before they expired, my chat was spammed with GTS notifications. I logged off and that's when my items dissappeared.
![2018-03-30_12 15 44](https://user-images.githubusercontent.com/37944220/38157079-f32acbe6-3448-11e8-93da-6b339f6e14fa.png)

**Comment by NickImpact** [comment]
Patched in the upcoming 3.8.0 build

**Comment by Rasgnarok** [comment]
Closing issue because we finally got rid of GTS, yay
