### ISSUE TITLE
Breeding speeds in filled ranch.

### ISSUE THREAD

**Issue by Vohras2** [ObliqueNET/Terra#89]
I have a ranch with 3 sets of water1 Pokemon. Lapras/Froakie, Froakie/Froakie, and Psyduck/Froakie. All in a single ranch in a breeding zone with full tier3 blocks. The first two breed at the expected speed, but the 3rd group always lags behind by several minutes.

**Comment by Rasgnarok** [comment]
Not a bug, closing.
