### ISSUE TITLE
Shopkeepers not working

### ISSUE THREAD

**Issue by Sweets143** [ObliqueNET/Terra#9]
Shopkeepers in the pokemart in Skadi are not working. This is the one downstairs and the two upstairs.

**Comment by Kayouri** [comment]
Please leave coords to any shopkeepers you find that aren't working.

**Comment by Sweets143** [comment]
407 80 -929 for the two upstairs that aren't working. The one downstairs is working again.

**Comment by Kayouri** [comment]
Fixed, now. Let us know if any others aren't working!
