### ISSUE TITLE
Blank screen

### ISSUE THREAD

**Issue by Mochiiaki** [ObliqueNET/Terra#97]
There is an issue that has presented itself in both singleplayer and multiplayer. At exactly Y-126 the screen goes out and completely blank. When the screen is like this, even when pressing escape you cannot see the buttons to leave the game. This is not a problem with vanilla so it must be a problems with the mod because even after restarting the game, launcher, and reloading chunks the issue is still present. I would like to please see this issue fixed soon as it is presenting many obstacles for me.

**Comment by Rasgnarok** [comment]
Can I have a log? Just checked this error and it honestly makes little sense to me

**Comment by Rasgnarok** [comment]
Closing issue for lack of information, please reopen if it continues~
