### ISSUE TITLE
Help I lost a Skarmory thanks

### ISSUE THREAD

**Issue by Austinator** [ObliqueNET/Terra#98]
Last night I bred some Skarmory bois and one of them was particularly good and threw it in Box 29 and today i logged on and it wasn't in any of my boxes I have a screenshot of its IVs here:
I think it had Sturdy but I'm not sure it was Impish nature I know.
If I could get it back that would be nice thanks.
![2018-05-20_20 15 37](https://user-images.githubusercontent.com/22136140/40334342-c185be2c-5d22-11e8-9e28-d9274c6cf844.png)

**Comment by starwarschamp4** [comment]
Was this solved already? If not, link this page in support in the discord.

**Comment by Rasgnarok** [comment]
Closing as it is outdated, please open a new one if this hasn't been refunded!
